# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  deepl-connector:
    # DeepL Authentication Key (should end with :fx)
    # https://www.deepl.com/docs-api/api-access/authentication/
    # [password]
    authKey: ''
