/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.AdminUsageReportUsageReportTotalUsage;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * Usage statistics for a specific API key and optionally a specific date.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class AdminUsageReportUsageReportGroupedUsage {
  @JsonProperty("api_key")
  private String apiKey = null;

  @JsonProperty("api_key_label")
  private String apiKeyLabel = null;

  @JsonProperty("usage_date")
  private OffsetDateTime usageDate = null;

  @JsonProperty("usage")
  private AdminUsageReportUsageReportTotalUsage usage = null;

  public AdminUsageReportUsageReportGroupedUsage apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Masked API key identifier.
   * @return apiKey
  **/
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public AdminUsageReportUsageReportGroupedUsage apiKeyLabel(String apiKeyLabel) {
    this.apiKeyLabel = apiKeyLabel;
    return this;
  }

   /**
   * Label associated with the API key.
   * @return apiKeyLabel
  **/
  public String getApiKeyLabel() {
    return apiKeyLabel;
  }

  public void setApiKeyLabel(String apiKeyLabel) {
    this.apiKeyLabel = apiKeyLabel;
  }

  public AdminUsageReportUsageReportGroupedUsage usageDate(OffsetDateTime usageDate) {
    this.usageDate = usageDate;
    return this;
  }

   /**
   * The usage date. Only present when group_by is \&quot;key_and_day\&quot;.
   * @return usageDate
  **/
  public OffsetDateTime getUsageDate() {
    return usageDate;
  }

  public void setUsageDate(OffsetDateTime usageDate) {
    this.usageDate = usageDate;
  }

  public AdminUsageReportUsageReportGroupedUsage usage(AdminUsageReportUsageReportTotalUsage usage) {
    this.usage = usage;
    return this;
  }

   /**
   * Get usage
   * @return usage
  **/
  public AdminUsageReportUsageReportTotalUsage getUsage() {
    return usage;
  }

  public void setUsage(AdminUsageReportUsageReportTotalUsage usage) {
    this.usage = usage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminUsageReportUsageReportGroupedUsage adminUsageReportUsageReportGroupedUsage = (AdminUsageReportUsageReportGroupedUsage) o;
    return Objects.equals(this.apiKey, adminUsageReportUsageReportGroupedUsage.apiKey) &&
        Objects.equals(this.apiKeyLabel, adminUsageReportUsageReportGroupedUsage.apiKeyLabel) &&
        Objects.equals(this.usageDate, adminUsageReportUsageReportGroupedUsage.usageDate) &&
        Objects.equals(this.usage, adminUsageReportUsageReportGroupedUsage.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, apiKeyLabel, usageDate, usage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminUsageReportUsageReportGroupedUsage {\n");
    
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    apiKeyLabel: ").append(toIndentedString(apiKeyLabel)).append("\n");
    sb.append("    usageDate: ").append(toIndentedString(usageDate)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
