/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.AdminUsageReportUsageReportGroupedUsage;
import com.deepl.api.v2.client.AdminUsageReportUsageReportTotalUsage;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * Contains the detailed usage statistics for the specified date range.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class AdminUsageReportData {
  @JsonProperty("total_usage")
  private AdminUsageReportUsageReportTotalUsage totalUsage = null;

  @JsonProperty("start_date")
  private OffsetDateTime startDate = null;

  @JsonProperty("end_date")
  private OffsetDateTime endDate = null;

  /**
   * The grouping method used, if any.
   */
  public enum GroupByEnum {
    KEY("key"),
    KEY_AND_DAY("key_and_day");

    private String value;

    GroupByEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static GroupByEnum fromValue(String input) {
      for (GroupByEnum b : GroupByEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("group_by")
  private GroupByEnum groupBy = null;

  @JsonProperty("grouped_usage")
  private List<AdminUsageReportUsageReportGroupedUsage> groupedUsage = null;

  public AdminUsageReportData totalUsage(AdminUsageReportUsageReportTotalUsage totalUsage) {
    this.totalUsage = totalUsage;
    return this;
  }

   /**
   * Get totalUsage
   * @return totalUsage
  **/
  public AdminUsageReportUsageReportTotalUsage getTotalUsage() {
    return totalUsage;
  }

  public void setTotalUsage(AdminUsageReportUsageReportTotalUsage totalUsage) {
    this.totalUsage = totalUsage;
  }

  public AdminUsageReportData startDate(OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Start date of the usage report period.
   * @return startDate
  **/
  public OffsetDateTime getStartDate() {
    return startDate;
  }

  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  public AdminUsageReportData endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * End date of the usage report period.
   * @return endDate
  **/
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public AdminUsageReportData groupBy(GroupByEnum groupBy) {
    this.groupBy = groupBy;
    return this;
  }

   /**
   * The grouping method used, if any.
   * @return groupBy
  **/
  public GroupByEnum getGroupBy() {
    return groupBy;
  }

  public void setGroupBy(GroupByEnum groupBy) {
    this.groupBy = groupBy;
  }

  public AdminUsageReportData groupedUsage(List<AdminUsageReportUsageReportGroupedUsage> groupedUsage) {
    this.groupedUsage = groupedUsage;
    return this;
  }

  public AdminUsageReportData addGroupedUsageItem(AdminUsageReportUsageReportGroupedUsage groupedUsageItem) {
    if (this.groupedUsage == null) {
      this.groupedUsage = new ArrayList<>();
    }
    this.groupedUsage.add(groupedUsageItem);
    return this;
  }

   /**
   * Array of usage statistics grouped by the specified criteria. Only present when group_by parameter is provided.
   * @return groupedUsage
  **/
  public List<AdminUsageReportUsageReportGroupedUsage> getGroupedUsage() {
    return groupedUsage;
  }

  public void setGroupedUsage(List<AdminUsageReportUsageReportGroupedUsage> groupedUsage) {
    this.groupedUsage = groupedUsage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminUsageReportData adminUsageReportData = (AdminUsageReportData) o;
    return Objects.equals(this.totalUsage, adminUsageReportData.totalUsage) &&
        Objects.equals(this.startDate, adminUsageReportData.startDate) &&
        Objects.equals(this.endDate, adminUsageReportData.endDate) &&
        Objects.equals(this.groupBy, adminUsageReportData.groupBy) &&
        Objects.equals(this.groupedUsage, adminUsageReportData.groupedUsage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalUsage, startDate, endDate, groupBy, groupedUsage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminUsageReportData {\n");
    
    sb.append("    totalUsage: ").append(toIndentedString(totalUsage)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    groupBy: ").append(toIndentedString(groupBy)).append("\n");
    sb.append("    groupedUsage: ").append(toIndentedString(groupedUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
