/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.V2admindeveloperkeysUsageLimits;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The API key.
 */
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class ApiKey {
  @JsonProperty("key_id")
  private String keyId = null;

  @JsonProperty("label")
  private String label = null;

  @JsonProperty("creation_time")
  private String creationTime = null;

  @JsonProperty("deactivated_time")
  private String deactivatedTime = null;

  @JsonProperty("is_deactivated")
  private Boolean isDeactivated = null;

  @JsonProperty("usage_limits")
  private V2admindeveloperkeysUsageLimits usageLimits = null;

  public ApiKey keyId(String keyId) {
    this.keyId = keyId;
    return this;
  }

   /**
   * API key ID. Consists of two valid GUIDs separated by a colon.
   * @return keyId
  **/
  public String getKeyId() {
    return keyId;
  }

  public void setKeyId(String keyId) {
    this.keyId = keyId;
  }

  public ApiKey label(String label) {
    this.label = label;
    return this;
  }

   /**
   * API key label. The default value is &#x60;DeepL API Key&#x60;.
   * @return label
  **/
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ApiKey creationTime(String creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Timestamp when the key was created (ISO 8601 format)
   * @return creationTime
  **/
  public String getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }

  public ApiKey deactivatedTime(String deactivatedTime) {
    this.deactivatedTime = deactivatedTime;
    return this;
  }

   /**
   * Timestamp when the key was deactivated (ISO 8601 format). The default value is &#x60;null&#x60;.
   * @return deactivatedTime
  **/
  public String getDeactivatedTime() {
    return deactivatedTime;
  }

  public void setDeactivatedTime(String deactivatedTime) {
    this.deactivatedTime = deactivatedTime;
  }

  public ApiKey isDeactivated(Boolean isDeactivated) {
    this.isDeactivated = isDeactivated;
    return this;
  }

   /**
   * Flag indicating whether the API key is deactivated. The default value is &#x60;false&#x60;.
   * @return isDeactivated
  **/
  public Boolean isIsDeactivated() {
    return isDeactivated;
  }

  public void setIsDeactivated(Boolean isDeactivated) {
    this.isDeactivated = isDeactivated;
  }

  public ApiKey usageLimits(V2admindeveloperkeysUsageLimits usageLimits) {
    this.usageLimits = usageLimits;
    return this;
  }

   /**
   * Get usageLimits
   * @return usageLimits
  **/
  public V2admindeveloperkeysUsageLimits getUsageLimits() {
    return usageLimits;
  }

  public void setUsageLimits(V2admindeveloperkeysUsageLimits usageLimits) {
    this.usageLimits = usageLimits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiKey apiKey = (ApiKey) o;
    return Objects.equals(this.keyId, apiKey.keyId) &&
        Objects.equals(this.label, apiKey.label) &&
        Objects.equals(this.creationTime, apiKey.creationTime) &&
        Objects.equals(this.deactivatedTime, apiKey.deactivatedTime) &&
        Objects.equals(this.isDeactivated, apiKey.isDeactivated) &&
        Objects.equals(this.usageLimits, apiKey.usageLimits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyId, label, creationTime, deactivatedTime, isDeactivated, usageLimits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiKey {\n");
    
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    deactivatedTime: ").append(toIndentedString(deactivatedTime)).append("\n");
    sb.append("    isDeactivated: ").append(toIndentedString(isDeactivated)).append("\n");
    sb.append("    usageLimits: ").append(toIndentedString(usageLimits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
