/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * DeveloperkeysLimitsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class DeveloperkeysLimitsBody {
  @JsonProperty("key_id")
  private String keyId = null;

  @JsonProperty("characters")
  private BigDecimal characters = null;

  public DeveloperkeysLimitsBody keyId(String keyId) {
    this.keyId = keyId;
    return this;
  }

   /**
   * API key ID. Consists of two valid GUIDs separated by a colon.
   * @return keyId
  **/
  public String getKeyId() {
    return keyId;
  }

  public void setKeyId(String keyId) {
    this.keyId = keyId;
  }

  public DeveloperkeysLimitsBody characters(BigDecimal characters) {
    this.characters = characters;
    return this;
  }

   /**
   * Restricts the number of total characters (across text translation, document translation, and text improvement) that can be consumed by an API key in a one-month usage period. Setting the limit to &#x60;0&#x60; means the API key will not be able to consume characters. Setting the limit to &#x60;null&#x60; disables the limit, effectively allowing unlimited usage. 
   * @return characters
  **/
  public BigDecimal getCharacters() {
    return characters;
  }

  public void setCharacters(BigDecimal characters) {
    this.characters = characters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeveloperkeysLimitsBody developerkeysLimitsBody = (DeveloperkeysLimitsBody) o;
    return Objects.equals(this.keyId, developerkeysLimitsBody.keyId) &&
        Objects.equals(this.characters, developerkeysLimitsBody.characters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyId, characters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeveloperkeysLimitsBody {\n");
    
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("    characters: ").append(toIndentedString(characters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
