/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages &#x60;DE&#x60; (German), &#x60;FR&#x60; (French), &#x60;IT&#x60; (Italian), &#x60;ES&#x60; (Spanish), &#x60;ES-419&#x60; (Latin American Spanish), &#x60;NL&#x60; (Dutch), &#x60;PL&#x60; (Polish), &#x60;PT-BR&#x60; and &#x60;PT-PT&#x60; (Portuguese), &#x60;JA&#x60; (Japanese), and &#x60;RU&#x60; (Russian). Learn more about the plain/polite feature for Japanese [here](https://support.deepl.com/hc/en-us/articles/6306700061852-About-the-plain-polite-feature-in-Japanese). Setting this parameter with a target language that does not support formality will fail, unless one of the &#x60;prefer_...&#x60; options are used. Possible options are:   * &#x60;default&#x60; (default)   * &#x60;more&#x60; - for a more formal language   * &#x60;less&#x60; - for a more informal language   * &#x60;prefer_more&#x60; - for a more formal language if available, otherwise fallback to default formality   * &#x60;prefer_less&#x60; - for a more informal language if available, otherwise fallback to default formality
 */
public enum Formality {
  DEFAULT("default"),
  MORE("more"),
  LESS("less"),
  PREFER_MORE("prefer_more"),
  PREFER_LESS("prefer_less");

  private String value;

  Formality(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Formality fromValue(String input) {
    for (Formality b : Formality.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
