/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GlossaryIdDictionariesBody1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class GlossaryIdDictionariesBody1 {
  /**
   * The language in which the source texts in the glossary are specified.
   */
  public enum SourceLangEnum {
    AR("ar"),
    BG("bg"),
    CS("cs"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    ES("es"),
    ET("et"),
    FI("fi"),
    FR("fr"),
    HE("he"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    LT("lt"),
    LV("lv"),
    NB("nb"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    SK("sk"),
    SL("sl"),
    SV("sv"),
    TH("th"),
    TR("tr"),
    UK("uk"),
    VI("vi"),
    ZH("zh");

    private String value;

    SourceLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceLangEnum fromValue(String input) {
      for (SourceLangEnum b : SourceLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_lang")
  private SourceLangEnum sourceLang = null;

  /**
   * The language in which the target texts in the glossary are specified.
   */
  public enum TargetLangEnum {
    AR("ar"),
    BG("bg"),
    CS("cs"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    ES("es"),
    ET("et"),
    FI("fi"),
    FR("fr"),
    HE("he"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    LT("lt"),
    LV("lv"),
    NB("nb"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    SK("sk"),
    SL("sl"),
    SV("sv"),
    TH("th"),
    TR("tr"),
    UK("uk"),
    VI("vi"),
    ZH("zh");

    private String value;

    TargetLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TargetLangEnum fromValue(String input) {
      for (TargetLangEnum b : TargetLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("target_lang")
  private TargetLangEnum targetLang = null;

  @JsonProperty("entries")
  private String entries = null;

  /**
   * The format in which the glossary entries are provided. Formats currently available: - &#x60;tsv&#x60; (default) - tab-separated values - &#x60;csv&#x60; - comma-separated values  See [Supported Glossary Formats](https://www.deepl.com/docs-api/glossaries/formats) for details about each format.
   */
  public enum EntriesFormatEnum {
    TSV("tsv"),
    CSV("csv");

    private String value;

    EntriesFormatEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EntriesFormatEnum fromValue(String input) {
      for (EntriesFormatEnum b : EntriesFormatEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("entries_format")
  private EntriesFormatEnum entriesFormat = EntriesFormatEnum.TSV;

  public GlossaryIdDictionariesBody1 sourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
    return this;
  }

   /**
   * The language in which the source texts in the glossary are specified.
   * @return sourceLang
  **/
  public SourceLangEnum getSourceLang() {
    return sourceLang;
  }

  public void setSourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
  }

  public GlossaryIdDictionariesBody1 targetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
    return this;
  }

   /**
   * The language in which the target texts in the glossary are specified.
   * @return targetLang
  **/
  public TargetLangEnum getTargetLang() {
    return targetLang;
  }

  public void setTargetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
  }

  public GlossaryIdDictionariesBody1 entries(String entries) {
    this.entries = entries;
    return this;
  }

   /**
   * The entries of the glossary. The entries have to be specified in the format provided by the &#x60;entries_format&#x60; parameter.
   * @return entries
  **/
  public String getEntries() {
    return entries;
  }

  public void setEntries(String entries) {
    this.entries = entries;
  }

  public GlossaryIdDictionariesBody1 entriesFormat(EntriesFormatEnum entriesFormat) {
    this.entriesFormat = entriesFormat;
    return this;
  }

   /**
   * The format in which the glossary entries are provided. Formats currently available: - &#x60;tsv&#x60; (default) - tab-separated values - &#x60;csv&#x60; - comma-separated values  See [Supported Glossary Formats](https://www.deepl.com/docs-api/glossaries/formats) for details about each format.
   * @return entriesFormat
  **/
  public EntriesFormatEnum getEntriesFormat() {
    return entriesFormat;
  }

  public void setEntriesFormat(EntriesFormatEnum entriesFormat) {
    this.entriesFormat = entriesFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GlossaryIdDictionariesBody1 glossaryIdDictionariesBody1 = (GlossaryIdDictionariesBody1) o;
    return Objects.equals(this.sourceLang, glossaryIdDictionariesBody1.sourceLang) &&
        Objects.equals(this.targetLang, glossaryIdDictionariesBody1.targetLang) &&
        Objects.equals(this.entries, glossaryIdDictionariesBody1.entries) &&
        Objects.equals(this.entriesFormat, glossaryIdDictionariesBody1.entriesFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceLang, targetLang, entries, entriesFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GlossaryIdDictionariesBody1 {\n");
    
    sb.append("    sourceLang: ").append(toIndentedString(sourceLang)).append("\n");
    sb.append("    targetLang: ").append(toIndentedString(targetLang)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    entriesFormat: ").append(toIndentedString(entriesFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
