/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The format in which the glossary entries are provided. Formats currently available: - &#x60;tsv&#x60; (default) - tab-separated values - &#x60;csv&#x60; - comma-separated values  See [Supported Glossary Formats](https://www.deepl.com/docs-api/glossaries/formats) for details about each format.
 */
public enum GlossaryEntriesFormat {
  TSV("tsv"),
  CSV("csv");

  private String value;

  GlossaryEntriesFormat(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static GlossaryEntriesFormat fromValue(String input) {
    for (GlossaryEntriesFormat b : GlossaryEntriesFormat.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
