/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The language in which the target texts in the glossary are specified.
 */
public enum GlossaryTargetLanguage {
  AR("ar"),
  BG("bg"),
  CS("cs"),
  DA("da"),
  DE("de"),
  EL("el"),
  EN("en"),
  ES("es"),
  ET("et"),
  FI("fi"),
  FR("fr"),
  HE("he"),
  HU("hu"),
  ID("id"),
  IT("it"),
  JA("ja"),
  KO("ko"),
  LT("lt"),
  LV("lv"),
  NB("nb"),
  NL("nl"),
  PL("pl"),
  PT("pt"),
  RO("ro"),
  RU("ru"),
  SK("sk"),
  SL("sl"),
  SV("sv"),
  TH("th"),
  TR("tr"),
  UK("uk"),
  VI("vi"),
  ZH("zh");

  private String value;

  GlossaryTargetLanguage(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static GlossaryTargetLanguage fromValue(String input) {
    for (GlossaryTargetLanguage b : GlossaryTargetLanguage.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
