/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse200Translations
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse200Translations {
  @JsonProperty("detected_source_language")
  private String detectedSourceLanguage = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("billed_characters")
  private Integer billedCharacters = null;

  @JsonProperty("model_type_used")
  private String modelTypeUsed = null;

  public InlineResponse200Translations detectedSourceLanguage(String detectedSourceLanguage) {
    this.detectedSourceLanguage = detectedSourceLanguage;
    return this;
  }

   /**
   * The language detected in the source text. It reflects the value of the &#x60;source_lang&#x60; parameter, when specified.
   * @return detectedSourceLanguage
  **/
  public String getDetectedSourceLanguage() {
    return detectedSourceLanguage;
  }

  public void setDetectedSourceLanguage(String detectedSourceLanguage) {
    this.detectedSourceLanguage = detectedSourceLanguage;
  }

  public InlineResponse200Translations text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The translated text.
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public InlineResponse200Translations billedCharacters(Integer billedCharacters) {
    this.billedCharacters = billedCharacters;
    return this;
  }

   /**
   * Number of characters counted by DeepL for billing purposes. Only present if the show_billed_characters parameter is set to true.
   * @return billedCharacters
  **/
  public Integer getBilledCharacters() {
    return billedCharacters;
  }

  public void setBilledCharacters(Integer billedCharacters) {
    this.billedCharacters = billedCharacters;
  }

  public InlineResponse200Translations modelTypeUsed(String modelTypeUsed) {
    this.modelTypeUsed = modelTypeUsed;
    return this;
  }

   /**
   * Indicates the translation model used. Only present if model_type parameter is included in the request.
   * @return modelTypeUsed
  **/
  public String getModelTypeUsed() {
    return modelTypeUsed;
  }

  public void setModelTypeUsed(String modelTypeUsed) {
    this.modelTypeUsed = modelTypeUsed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200Translations inlineResponse200Translations = (InlineResponse200Translations) o;
    return Objects.equals(this.detectedSourceLanguage, inlineResponse200Translations.detectedSourceLanguage) &&
        Objects.equals(this.text, inlineResponse200Translations.text) &&
        Objects.equals(this.billedCharacters, inlineResponse200Translations.billedCharacters) &&
        Objects.equals(this.modelTypeUsed, inlineResponse200Translations.modelTypeUsed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detectedSourceLanguage, text, billedCharacters, modelTypeUsed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200Translations {\n");
    
    sb.append("    detectedSourceLanguage: ").append(toIndentedString(detectedSourceLanguage)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    billedCharacters: ").append(toIndentedString(billedCharacters)).append("\n");
    sb.append("    modelTypeUsed: ").append(toIndentedString(modelTypeUsed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
