/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse2002
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2002 {
  @JsonProperty("document_id")
  private String documentId = null;

  /**
   * A short description of the state the document translation process is currently in. Possible values are:  * &#x60;queued&#x60; - the translation job is waiting in line to be processed  * &#x60;translating&#x60; - the translation is currently ongoing  * &#x60;done&#x60; - the translation is done and the translated document is ready for download  * &#x60;error&#x60; - an irrecoverable error occurred while translating the document
   */
  public enum StatusEnum {
    QUEUED("queued"),
    TRANSLATING("translating"),
    DONE("done"),
    ERROR("error");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("seconds_remaining")
  private Integer secondsRemaining = null;

  @JsonProperty("billed_characters")
  private Integer billedCharacters = null;

  @JsonProperty("error_message")
  private String errorMessage = null;

  public InlineResponse2002 documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * A unique ID assigned to the uploaded document and the requested translation process. The same ID that was used when requesting the translation status.
   * @return documentId
  **/
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public InlineResponse2002 status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * A short description of the state the document translation process is currently in. Possible values are:  * &#x60;queued&#x60; - the translation job is waiting in line to be processed  * &#x60;translating&#x60; - the translation is currently ongoing  * &#x60;done&#x60; - the translation is done and the translated document is ready for download  * &#x60;error&#x60; - an irrecoverable error occurred while translating the document
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public InlineResponse2002 secondsRemaining(Integer secondsRemaining) {
    this.secondsRemaining = secondsRemaining;
    return this;
  }

   /**
   * Estimated number of seconds until the translation is done. This parameter is only included while &#x60;status&#x60; is &#x60;\&quot;translating\&quot;&#x60;.
   * @return secondsRemaining
  **/
  public Integer getSecondsRemaining() {
    return secondsRemaining;
  }

  public void setSecondsRemaining(Integer secondsRemaining) {
    this.secondsRemaining = secondsRemaining;
  }

  public InlineResponse2002 billedCharacters(Integer billedCharacters) {
    this.billedCharacters = billedCharacters;
    return this;
  }

   /**
   * The number of characters billed to your account. The characters will only be billed after a successful download request.
   * @return billedCharacters
  **/
  public Integer getBilledCharacters() {
    return billedCharacters;
  }

  public void setBilledCharacters(Integer billedCharacters) {
    this.billedCharacters = billedCharacters;
  }

  public InlineResponse2002 errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * A short description of the error, if available. Note that the content is subject to change. This parameter may be included if an error occurred during translation.
   * @return errorMessage
  **/
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.documentId, inlineResponse2002.documentId) &&
        Objects.equals(this.status, inlineResponse2002.status) &&
        Objects.equals(this.secondsRemaining, inlineResponse2002.secondsRemaining) &&
        Objects.equals(this.billedCharacters, inlineResponse2002.billedCharacters) &&
        Objects.equals(this.errorMessage, inlineResponse2002.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, status, secondsRemaining, billedCharacters, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    secondsRemaining: ").append(toIndentedString(secondsRemaining)).append("\n");
    sb.append("    billedCharacters: ").append(toIndentedString(billedCharacters)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
