/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
/**
 * InlineResponse2011
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2011 {
  @JsonProperty("glossary_id")
  private String glossaryId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("ready")
  private Boolean ready = null;

  /**
   * The language in which the source texts in the glossary are specified.
   */
  public enum SourceLangEnum {
    AR("ar"),
    BG("bg"),
    CS("cs"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    ES("es"),
    ET("et"),
    FI("fi"),
    FR("fr"),
    HE("he"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    LT("lt"),
    LV("lv"),
    NB("nb"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    SK("sk"),
    SL("sl"),
    SV("sv"),
    TH("th"),
    TR("tr"),
    UK("uk"),
    VI("vi"),
    ZH("zh");

    private String value;

    SourceLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceLangEnum fromValue(String input) {
      for (SourceLangEnum b : SourceLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_lang")
  private SourceLangEnum sourceLang = null;

  /**
   * The language in which the target texts in the glossary are specified.
   */
  public enum TargetLangEnum {
    AR("ar"),
    BG("bg"),
    CS("cs"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    ES("es"),
    ET("et"),
    FI("fi"),
    FR("fr"),
    HE("he"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    LT("lt"),
    LV("lv"),
    NB("nb"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    SK("sk"),
    SL("sl"),
    SV("sv"),
    TH("th"),
    TR("tr"),
    UK("uk"),
    VI("vi"),
    ZH("zh");

    private String value;

    TargetLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TargetLangEnum fromValue(String input) {
      for (TargetLangEnum b : TargetLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("target_lang")
  private TargetLangEnum targetLang = null;

  @JsonProperty("creation_time")
  private OffsetDateTime creationTime = null;

  @JsonProperty("entry_count")
  private Integer entryCount = null;

  public InlineResponse2011 glossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
    return this;
  }

   /**
   * A unique ID assigned to a glossary.
   * @return glossaryId
  **/
  public String getGlossaryId() {
    return glossaryId;
  }

  public void setGlossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
  }

  public InlineResponse2011 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name associated with the glossary.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2011 ready(Boolean ready) {
    this.ready = ready;
    return this;
  }

   /**
   * Indicates if the newly created glossary can already be used in &#x60;translate&#x60; requests. If the created glossary is not yet ready, you have to wait and check the &#x60;ready&#x60; status of the glossary before using it in a &#x60;translate&#x60; request.
   * @return ready
  **/
  public Boolean isReady() {
    return ready;
  }

  public void setReady(Boolean ready) {
    this.ready = ready;
  }

  public InlineResponse2011 sourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
    return this;
  }

   /**
   * The language in which the source texts in the glossary are specified.
   * @return sourceLang
  **/
  public SourceLangEnum getSourceLang() {
    return sourceLang;
  }

  public void setSourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
  }

  public InlineResponse2011 targetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
    return this;
  }

   /**
   * The language in which the target texts in the glossary are specified.
   * @return targetLang
  **/
  public TargetLangEnum getTargetLang() {
    return targetLang;
  }

  public void setTargetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
  }

  public InlineResponse2011 creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * The creation time of the glossary in the ISO 8601-1:2019 format (e.g.: &#x60;2021-08-03T14:16:18.329Z&#x60;).
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }

  public InlineResponse2011 entryCount(Integer entryCount) {
    this.entryCount = entryCount;
    return this;
  }

   /**
   * The number of entries in the glossary.
   * @return entryCount
  **/
  public Integer getEntryCount() {
    return entryCount;
  }

  public void setEntryCount(Integer entryCount) {
    this.entryCount = entryCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2011 inlineResponse2011 = (InlineResponse2011) o;
    return Objects.equals(this.glossaryId, inlineResponse2011.glossaryId) &&
        Objects.equals(this.name, inlineResponse2011.name) &&
        Objects.equals(this.ready, inlineResponse2011.ready) &&
        Objects.equals(this.sourceLang, inlineResponse2011.sourceLang) &&
        Objects.equals(this.targetLang, inlineResponse2011.targetLang) &&
        Objects.equals(this.creationTime, inlineResponse2011.creationTime) &&
        Objects.equals(this.entryCount, inlineResponse2011.entryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(glossaryId, name, ready, sourceLang, targetLang, creationTime, entryCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2011 {\n");
    
    sb.append("    glossaryId: ").append(toIndentedString(glossaryId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    sourceLang: ").append(toIndentedString(sourceLang)).append("\n");
    sb.append("    targetLang: ").append(toIndentedString(targetLang)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    entryCount: ").append(toIndentedString(entryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
