/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse2007Improvements
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2007Improvements {
  @JsonProperty("detected_source_language")
  private String detectedSourceLanguage = null;

  @JsonProperty("text")
  private String text = null;

  public InlineResponse2007Improvements detectedSourceLanguage(String detectedSourceLanguage) {
    this.detectedSourceLanguage = detectedSourceLanguage;
    return this;
  }

   /**
   * The language detected in the source text.
   * @return detectedSourceLanguage
  **/
  public String getDetectedSourceLanguage() {
    return detectedSourceLanguage;
  }

  public void setDetectedSourceLanguage(String detectedSourceLanguage) {
    this.detectedSourceLanguage = detectedSourceLanguage;
  }

  public InlineResponse2007Improvements text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The improved text.
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007Improvements inlineResponse2007Improvements = (InlineResponse2007Improvements) o;
    return Objects.equals(this.detectedSourceLanguage, inlineResponse2007Improvements.detectedSourceLanguage) &&
        Objects.equals(this.text, inlineResponse2007Improvements.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detectedSourceLanguage, text);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007Improvements {\n");
    
    sb.append("    detectedSourceLanguage: ").append(toIndentedString(detectedSourceLanguage)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
