/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.InlineResponse2007Improvements;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2007
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2007 {
  @JsonProperty("improvements")
  private List<InlineResponse2007Improvements> improvements = null;

  public InlineResponse2007 improvements(List<InlineResponse2007Improvements> improvements) {
    this.improvements = improvements;
    return this;
  }

  public InlineResponse2007 addImprovementsItem(InlineResponse2007Improvements improvementsItem) {
    if (this.improvements == null) {
      this.improvements = new ArrayList<>();
    }
    this.improvements.add(improvementsItem);
    return this;
  }

   /**
   * Get improvements
   * @return improvements
  **/
  public List<InlineResponse2007Improvements> getImprovements() {
    return improvements;
  }

  public void setImprovements(List<InlineResponse2007Improvements> improvements) {
    this.improvements = improvements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2007 inlineResponse2007 = (InlineResponse2007) o;
    return Objects.equals(this.improvements, inlineResponse2007.improvements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(improvements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2007 {\n");
    
    sb.append("    improvements: ").append(toIndentedString(improvements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
