/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.InlineResponse2006Glossaries;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2006
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2006 {
  @JsonProperty("glossaries")
  private List<InlineResponse2006Glossaries> glossaries = null;

  public InlineResponse2006 glossaries(List<InlineResponse2006Glossaries> glossaries) {
    this.glossaries = glossaries;
    return this;
  }

  public InlineResponse2006 addGlossariesItem(InlineResponse2006Glossaries glossariesItem) {
    if (this.glossaries == null) {
      this.glossaries = new ArrayList<>();
    }
    this.glossaries.add(glossariesItem);
    return this;
  }

   /**
   * Get glossaries
   * @return glossaries
  **/
  public List<InlineResponse2006Glossaries> getGlossaries() {
    return glossaries;
  }

  public void setGlossaries(List<InlineResponse2006Glossaries> glossaries) {
    this.glossaries = glossaries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2006 inlineResponse2006 = (InlineResponse2006) o;
    return Objects.equals(this.glossaries, inlineResponse2006.glossaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(glossaries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2006 {\n");
    
    sb.append("    glossaries: ").append(toIndentedString(glossaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
