/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.UsageResponseProducts;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2008
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2008 {
  @JsonProperty("character_count")
  private Long characterCount = null;

  @JsonProperty("character_limit")
  private Long characterLimit = null;

  @JsonProperty("products")
  private List<UsageResponseProducts> products = null;

  @JsonProperty("api_key_character_count")
  private Integer apiKeyCharacterCount = null;

  @JsonProperty("api_key_character_limit")
  private Integer apiKeyCharacterLimit = null;

  @JsonProperty("speech_to_text_milliseconds_count")
  private Integer speechToTextMillisecondsCount = null;

  @JsonProperty("speech_to_text_milliseconds_limit")
  private Integer speechToTextMillisecondsLimit = null;

  @JsonProperty("start_time")
  private OffsetDateTime startTime = null;

  @JsonProperty("end_time")
  private OffsetDateTime endTime = null;

  public InlineResponse2008 characterCount(Long characterCount) {
    this.characterCount = characterCount;
    return this;
  }

   /**
   * Characters translated so far in the current billing period.
   * @return characterCount
  **/
  public Long getCharacterCount() {
    return characterCount;
  }

  public void setCharacterCount(Long characterCount) {
    this.characterCount = characterCount;
  }

  public InlineResponse2008 characterLimit(Long characterLimit) {
    this.characterLimit = characterLimit;
    return this;
  }

   /**
   * Current maximum number of characters that can be translated per billing period. If cost control is set, the cost control limit will be returned in this field.
   * @return characterLimit
  **/
  public Long getCharacterLimit() {
    return characterLimit;
  }

  public void setCharacterLimit(Long characterLimit) {
    this.characterLimit = characterLimit;
  }

  public InlineResponse2008 products(List<UsageResponseProducts> products) {
    this.products = products;
    return this;
  }

  public InlineResponse2008 addProductsItem(UsageResponseProducts productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Only present for API Pro users. Per-product usage details.
   * @return products
  **/
  public List<UsageResponseProducts> getProducts() {
    return products;
  }

  public void setProducts(List<UsageResponseProducts> products) {
    this.products = products;
  }

  public InlineResponse2008 apiKeyCharacterCount(Integer apiKeyCharacterCount) {
    this.apiKeyCharacterCount = apiKeyCharacterCount;
    return this;
  }

   /**
   * Only present for API Pro users. Total characters used by this API key in the current period.
   * @return apiKeyCharacterCount
  **/
  public Integer getApiKeyCharacterCount() {
    return apiKeyCharacterCount;
  }

  public void setApiKeyCharacterCount(Integer apiKeyCharacterCount) {
    this.apiKeyCharacterCount = apiKeyCharacterCount;
  }

  public InlineResponse2008 apiKeyCharacterLimit(Integer apiKeyCharacterLimit) {
    this.apiKeyCharacterLimit = apiKeyCharacterLimit;
    return this;
  }

   /**
   * Only present for API Pro users. Character limit for this API key in the current period.
   * @return apiKeyCharacterLimit
  **/
  public Integer getApiKeyCharacterLimit() {
    return apiKeyCharacterLimit;
  }

  public void setApiKeyCharacterLimit(Integer apiKeyCharacterLimit) {
    this.apiKeyCharacterLimit = apiKeyCharacterLimit;
  }

  public InlineResponse2008 speechToTextMillisecondsCount(Integer speechToTextMillisecondsCount) {
    this.speechToTextMillisecondsCount = speechToTextMillisecondsCount;
    return this;
  }

   /**
   * Only present for API Pro users. Milliseconds of speech-to-text used in the current period.
   * @return speechToTextMillisecondsCount
  **/
  public Integer getSpeechToTextMillisecondsCount() {
    return speechToTextMillisecondsCount;
  }

  public void setSpeechToTextMillisecondsCount(Integer speechToTextMillisecondsCount) {
    this.speechToTextMillisecondsCount = speechToTextMillisecondsCount;
  }

  public InlineResponse2008 speechToTextMillisecondsLimit(Integer speechToTextMillisecondsLimit) {
    this.speechToTextMillisecondsLimit = speechToTextMillisecondsLimit;
    return this;
  }

   /**
   * Only present for API Pro users. Milliseconds of speech-to-text limit in the current period.
   * @return speechToTextMillisecondsLimit
  **/
  public Integer getSpeechToTextMillisecondsLimit() {
    return speechToTextMillisecondsLimit;
  }

  public void setSpeechToTextMillisecondsLimit(Integer speechToTextMillisecondsLimit) {
    this.speechToTextMillisecondsLimit = speechToTextMillisecondsLimit;
  }

  public InlineResponse2008 startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Only present for API Pro users. Start time of the current billing period (ISO 8601).
   * @return startTime
  **/
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public InlineResponse2008 endTime(OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Only present for API Pro users. End time of the current billing period (ISO 8601).
   * @return endTime
  **/
  public OffsetDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2008 inlineResponse2008 = (InlineResponse2008) o;
    return Objects.equals(this.characterCount, inlineResponse2008.characterCount) &&
        Objects.equals(this.characterLimit, inlineResponse2008.characterLimit) &&
        Objects.equals(this.products, inlineResponse2008.products) &&
        Objects.equals(this.apiKeyCharacterCount, inlineResponse2008.apiKeyCharacterCount) &&
        Objects.equals(this.apiKeyCharacterLimit, inlineResponse2008.apiKeyCharacterLimit) &&
        Objects.equals(this.speechToTextMillisecondsCount, inlineResponse2008.speechToTextMillisecondsCount) &&
        Objects.equals(this.speechToTextMillisecondsLimit, inlineResponse2008.speechToTextMillisecondsLimit) &&
        Objects.equals(this.startTime, inlineResponse2008.startTime) &&
        Objects.equals(this.endTime, inlineResponse2008.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(characterCount, characterLimit, products, apiKeyCharacterCount, apiKeyCharacterLimit, speechToTextMillisecondsCount, speechToTextMillisecondsLimit, startTime, endTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2008 {\n");
    
    sb.append("    characterCount: ").append(toIndentedString(characterCount)).append("\n");
    sb.append("    characterLimit: ").append(toIndentedString(characterLimit)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    apiKeyCharacterCount: ").append(toIndentedString(apiKeyCharacterCount)).append("\n");
    sb.append("    apiKeyCharacterLimit: ").append(toIndentedString(apiKeyCharacterLimit)).append("\n");
    sb.append("    speechToTextMillisecondsCount: ").append(toIndentedString(speechToTextMillisecondsCount)).append("\n");
    sb.append("    speechToTextMillisecondsLimit: ").append(toIndentedString(speechToTextMillisecondsLimit)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
