/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse2009
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2009 {
  @JsonProperty("language")
  private String language = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("supports_formality")
  private Boolean supportsFormality = null;

  public InlineResponse2009 language(String language) {
    this.language = language;
    return this;
  }

   /**
   * The language code of the given language.
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public InlineResponse2009 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the language in English.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2009 supportsFormality(Boolean supportsFormality) {
    this.supportsFormality = supportsFormality;
    return this;
  }

   /**
   * Denotes formality support in case of a target language listing.
   * @return supportsFormality
  **/
  public Boolean isSupportsFormality() {
    return supportsFormality;
  }

  public void setSupportsFormality(Boolean supportsFormality) {
    this.supportsFormality = supportsFormality;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009 inlineResponse2009 = (InlineResponse2009) o;
    return Objects.equals(this.language, inlineResponse2009.language) &&
        Objects.equals(this.name, inlineResponse2009.name) &&
        Objects.equals(this.supportsFormality, inlineResponse2009.supportsFormality);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, name, supportsFormality);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009 {\n");
    
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supportsFormality: ").append(toIndentedString(supportsFormality)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
