/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.InlineResponse2003SupportedLanguages;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2003
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2003 {
  @JsonProperty("supported_languages")
  private List<InlineResponse2003SupportedLanguages> supportedLanguages = null;

  public InlineResponse2003 supportedLanguages(List<InlineResponse2003SupportedLanguages> supportedLanguages) {
    this.supportedLanguages = supportedLanguages;
    return this;
  }

  public InlineResponse2003 addSupportedLanguagesItem(InlineResponse2003SupportedLanguages supportedLanguagesItem) {
    if (this.supportedLanguages == null) {
      this.supportedLanguages = new ArrayList<>();
    }
    this.supportedLanguages.add(supportedLanguagesItem);
    return this;
  }

   /**
   * The list of supported languages
   * @return supportedLanguages
  **/
  public List<InlineResponse2003SupportedLanguages> getSupportedLanguages() {
    return supportedLanguages;
  }

  public void setSupportedLanguages(List<InlineResponse2003SupportedLanguages> supportedLanguages) {
    this.supportedLanguages = supportedLanguages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return Objects.equals(this.supportedLanguages, inlineResponse2003.supportedLanguages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(supportedLanguages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("    supportedLanguages: ").append(toIndentedString(supportedLanguages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
