/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse20012
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse20012 {
  @JsonProperty("streaming_url")
  private String streamingUrl = null;

  @JsonProperty("token")
  private String token = null;

  public InlineResponse20012 streamingUrl(String streamingUrl) {
    this.streamingUrl = streamingUrl;
    return this;
  }

   /**
   * The WebSocket URL to use for establishing the streaming connection. This URL is ephemeral and valid for one-time use only.
   * @return streamingUrl
  **/
  public String getStreamingUrl() {
    return streamingUrl;
  }

  public void setStreamingUrl(String streamingUrl) {
    this.streamingUrl = streamingUrl;
  }

  public InlineResponse20012 token(String token) {
    this.token = token;
    return this;
  }

   /**
   * A unique ephemeral token for authentication with the streaming endpoint. Pass this as a query parameter when connecting to the WebSocket URL.
   * @return token
  **/
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012 inlineResponse20012 = (InlineResponse20012) o;
    return Objects.equals(this.streamingUrl, inlineResponse20012.streamingUrl) &&
        Objects.equals(this.token, inlineResponse20012.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(streamingUrl, token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012 {\n");
    
    sb.append("    streamingUrl: ").append(toIndentedString(streamingUrl)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
