/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InlineResponse2003SupportedLanguages
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class InlineResponse2003SupportedLanguages {
  @JsonProperty("source_lang")
  private String sourceLang = null;

  @JsonProperty("target_lang")
  private String targetLang = null;

  public InlineResponse2003SupportedLanguages sourceLang(String sourceLang) {
    this.sourceLang = sourceLang;
    return this;
  }

   /**
   * The language in which the source texts in the glossary are specified.
   * @return sourceLang
  **/
  public String getSourceLang() {
    return sourceLang;
  }

  public void setSourceLang(String sourceLang) {
    this.sourceLang = sourceLang;
  }

  public InlineResponse2003SupportedLanguages targetLang(String targetLang) {
    this.targetLang = targetLang;
    return this;
  }

   /**
   * The language in which the target texts in the glossary are specified.
   * @return targetLang
  **/
  public String getTargetLang() {
    return targetLang;
  }

  public void setTargetLang(String targetLang) {
    this.targetLang = targetLang;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003SupportedLanguages inlineResponse2003SupportedLanguages = (InlineResponse2003SupportedLanguages) o;
    return Objects.equals(this.sourceLang, inlineResponse2003SupportedLanguages.sourceLang) &&
        Objects.equals(this.targetLang, inlineResponse2003SupportedLanguages.targetLang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceLang, targetLang);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003SupportedLanguages {\n");
    
    sb.append("    sourceLang: ").append(toIndentedString(sourceLang)).append("\n");
    sb.append("    targetLang: ").append(toIndentedString(targetLang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
