/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies which DeepL model should be used for translation.  Possible values are: * &#x60;latency_optimized&#x60; (default) - uses lower latency “classic” translation models, which support all language pairs;   default value * &#x60;quality_optimized&#x60; - uses higher latency, improved quality “next-gen” translation models, which support only a   subset of language pairs; if a language pair that is not supported by next-gen models is included in the   request, it will fail. Consider using prefer_quality_optimized instead. * &#x60;prefer_quality_optimized&#x60; - prioritizes use of higher latency, improved quality “next-gen” translation models,   which support only a subset of DeepL languages; if a request includes a language pair not supported by   next-gen models, the request will fall back to latency_optimized classic models.
 */
public enum ModelType {
  QUALITY_OPTIMIZED("quality_optimized"),
  PREFER_QUALITY_OPTIMIZED("prefer_quality_optimized"),
  LATENCY_OPTIMIZED("latency_optimized");

  private String value;

  ModelType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ModelType fromValue(String input) {
    for (ModelType b : ModelType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
