/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.MultilingualGlossaryEntriesInformation;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * MultilingualGlossaryEntriesResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class MultilingualGlossaryEntriesResponse {
  @JsonProperty("dictionaries")
  private List<MultilingualGlossaryEntriesInformation> dictionaries = null;

  public MultilingualGlossaryEntriesResponse dictionaries(List<MultilingualGlossaryEntriesInformation> dictionaries) {
    this.dictionaries = dictionaries;
    return this;
  }

  public MultilingualGlossaryEntriesResponse addDictionariesItem(MultilingualGlossaryEntriesInformation dictionariesItem) {
    if (this.dictionaries == null) {
      this.dictionaries = new ArrayList<>();
    }
    this.dictionaries.add(dictionariesItem);
    return this;
  }

   /**
   * Get dictionaries
   * @return dictionaries
  **/
  public List<MultilingualGlossaryEntriesInformation> getDictionaries() {
    return dictionaries;
  }

  public void setDictionaries(List<MultilingualGlossaryEntriesInformation> dictionaries) {
    this.dictionaries = dictionaries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultilingualGlossaryEntriesResponse multilingualGlossaryEntriesResponse = (MultilingualGlossaryEntriesResponse) o;
    return Objects.equals(this.dictionaries, multilingualGlossaryEntriesResponse.dictionaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dictionaries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultilingualGlossaryEntriesResponse {\n");
    
    sb.append("    dictionaries: ").append(toIndentedString(dictionaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
