/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.V3glossariesDictionaries;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
/**
 * MultilingualGlossary
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class MultilingualGlossary {
  @JsonProperty("glossary_id")
  private String glossaryId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("dictionaries")
  private List<V3glossariesDictionaries> dictionaries = null;

  @JsonProperty("creation_time")
  private OffsetDateTime creationTime = null;

  public MultilingualGlossary glossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
    return this;
  }

   /**
   * A unique ID assigned to a glossary.
   * @return glossaryId
  **/
  public String getGlossaryId() {
    return glossaryId;
  }

  public void setGlossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
  }

  public MultilingualGlossary name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name associated with the glossary.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MultilingualGlossary dictionaries(List<V3glossariesDictionaries> dictionaries) {
    this.dictionaries = dictionaries;
    return this;
  }

  public MultilingualGlossary addDictionariesItem(V3glossariesDictionaries dictionariesItem) {
    if (this.dictionaries == null) {
      this.dictionaries = new ArrayList<>();
    }
    this.dictionaries.add(dictionariesItem);
    return this;
  }

   /**
   * List of dictionaries contained in this glossary. Each dictionary contains a source and target language, as well as pairs of source and target entries.
   * @return dictionaries
  **/
  public List<V3glossariesDictionaries> getDictionaries() {
    return dictionaries;
  }

  public void setDictionaries(List<V3glossariesDictionaries> dictionaries) {
    this.dictionaries = dictionaries;
  }

  public MultilingualGlossary creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * The creation time of the glossary in the ISO 8601-1:2019 format (e.g.: &#x60;2021-08-03T14:16:18.329Z&#x60;).
   * @return creationTime
  **/
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultilingualGlossary multilingualGlossary = (MultilingualGlossary) o;
    return Objects.equals(this.glossaryId, multilingualGlossary.glossaryId) &&
        Objects.equals(this.name, multilingualGlossary.name) &&
        Objects.equals(this.dictionaries, multilingualGlossary.dictionaries) &&
        Objects.equals(this.creationTime, multilingualGlossary.creationTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(glossaryId, name, dictionaries, creationTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultilingualGlossary {\n");
    
    sb.append("    glossaryId: ").append(toIndentedString(glossaryId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dictionaries: ").append(toIndentedString(dictionaries)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
