/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MultilingualGlossaryEntriesInformation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class MultilingualGlossaryEntriesInformation {
  /**
   * The language in which the source texts in the glossary are specified.
   */
  public enum SourceLangEnum {
    AR("ar"),
    BG("bg"),
    CS("cs"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    ES("es"),
    ET("et"),
    FI("fi"),
    FR("fr"),
    HE("he"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    LT("lt"),
    LV("lv"),
    NB("nb"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    SK("sk"),
    SL("sl"),
    SV("sv"),
    TH("th"),
    TR("tr"),
    UK("uk"),
    VI("vi"),
    ZH("zh");

    private String value;

    SourceLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceLangEnum fromValue(String input) {
      for (SourceLangEnum b : SourceLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_lang")
  private SourceLangEnum sourceLang = null;

  /**
   * The language in which the target texts in the glossary are specified.
   */
  public enum TargetLangEnum {
    AR("ar"),
    BG("bg"),
    CS("cs"),
    DA("da"),
    DE("de"),
    EL("el"),
    EN("en"),
    ES("es"),
    ET("et"),
    FI("fi"),
    FR("fr"),
    HE("he"),
    HU("hu"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    LT("lt"),
    LV("lv"),
    NB("nb"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    SK("sk"),
    SL("sl"),
    SV("sv"),
    TH("th"),
    TR("tr"),
    UK("uk"),
    VI("vi"),
    ZH("zh");

    private String value;

    TargetLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TargetLangEnum fromValue(String input) {
      for (TargetLangEnum b : TargetLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("target_lang")
  private TargetLangEnum targetLang = null;

  @JsonProperty("entry_count")
  private Integer entryCount = null;

  public MultilingualGlossaryEntriesInformation sourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
    return this;
  }

   /**
   * The language in which the source texts in the glossary are specified.
   * @return sourceLang
  **/
  public SourceLangEnum getSourceLang() {
    return sourceLang;
  }

  public void setSourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
  }

  public MultilingualGlossaryEntriesInformation targetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
    return this;
  }

   /**
   * The language in which the target texts in the glossary are specified.
   * @return targetLang
  **/
  public TargetLangEnum getTargetLang() {
    return targetLang;
  }

  public void setTargetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
  }

  public MultilingualGlossaryEntriesInformation entryCount(Integer entryCount) {
    this.entryCount = entryCount;
    return this;
  }

   /**
   * The number of entries in the glossary.
   * @return entryCount
  **/
  public Integer getEntryCount() {
    return entryCount;
  }

  public void setEntryCount(Integer entryCount) {
    this.entryCount = entryCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultilingualGlossaryEntriesInformation multilingualGlossaryEntriesInformation = (MultilingualGlossaryEntriesInformation) o;
    return Objects.equals(this.sourceLang, multilingualGlossaryEntriesInformation.sourceLang) &&
        Objects.equals(this.targetLang, multilingualGlossaryEntriesInformation.targetLang) &&
        Objects.equals(this.entryCount, multilingualGlossaryEntriesInformation.entryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceLang, targetLang, entryCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultilingualGlossaryEntriesInformation {\n");
    
    sb.append("    sourceLang: ").append(toIndentedString(sourceLang)).append("\n");
    sb.append("    targetLang: ").append(toIndentedString(targetLang)).append("\n");
    sb.append("    entryCount: ").append(toIndentedString(entryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
