/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The automatic detection of the XML structure won&#x27;t yield best results in all XML files. You can disable this automatic mechanism altogether by setting the &#x60;outline_detection&#x60; parameter to &#x60;0&#x60; and selecting the tags that should be considered structure tags. This will split sentences using the &#x60;splitting_tags&#x60; parameter.   In the example below, we achieve the same results as the automatic engine by disabling automatic detection with &#x60;outline_detection&#x3D;0&#x60; and setting the parameters manually to &#x60;tag_handling&#x3D;xml&#x60;, &#x60;split_sentences&#x3D;nonewlines&#x60;,  and &#x60;splitting_tags&#x3D;par,title&#x60;.  * Example request:    &#x60;&#x60;&#x60;    &lt;document&gt;      &lt;meta&gt;        &lt;title&gt;A document&#x27;s title&lt;/title&gt;      &lt;/meta&gt;      &lt;content&gt;        &lt;par&gt;This is the first sentence. Followed by a second one.&lt;/par&gt;        &lt;par&gt;This is the third sentence.&lt;/par&gt;      &lt;/content&gt;    &lt;/document&gt;    &#x60;&#x60;&#x60;  * Example response:    &#x60;&#x60;&#x60;    &lt;document&gt;      &lt;meta&gt;        &lt;title&gt;Der Titel eines Dokuments&lt;/title&gt;      &lt;/meta&gt;      &lt;content&gt;        &lt;par&gt;Das ist der erste Satz. Gefolgt von einem zweiten.&lt;/par&gt;        &lt;par&gt;Dies ist der dritte Satz.&lt;/par&gt;      &lt;/content&gt;    &lt;/document&gt;    &#x60;&#x60;&#x60; While this approach is slightly more complicated, it allows for greater control over the structure of the translation output.
 */
public enum OutlineDetectionOptionStr {
  _0("0");

  private String value;

  OutlineDetectionOptionStr(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static OutlineDetectionOptionStr fromValue(String input) {
    for (OutlineDetectionOptionStr b : OutlineDetectionOptionStr.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
