/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.deepl.api.v2.client.V3glossariesDictionaries;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * PatchMultilingualGlossaryParameters
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class PatchMultilingualGlossaryParameters {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("dictionaries")
  private List<V3glossariesDictionaries> dictionaries = null;

  public PatchMultilingualGlossaryParameters name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A unique ID assigned to a glossary.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PatchMultilingualGlossaryParameters dictionaries(List<V3glossariesDictionaries> dictionaries) {
    this.dictionaries = dictionaries;
    return this;
  }

  public PatchMultilingualGlossaryParameters addDictionariesItem(V3glossariesDictionaries dictionariesItem) {
    if (this.dictionaries == null) {
      this.dictionaries = new ArrayList<>();
    }
    this.dictionaries.add(dictionariesItem);
    return this;
  }

   /**
   * Dictionaries to edit the glossary with. Currently only supports 0 or 1 dictionaries in the array.
   * @return dictionaries
  **/
  public List<V3glossariesDictionaries> getDictionaries() {
    return dictionaries;
  }

  public void setDictionaries(List<V3glossariesDictionaries> dictionaries) {
    this.dictionaries = dictionaries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchMultilingualGlossaryParameters patchMultilingualGlossaryParameters = (PatchMultilingualGlossaryParameters) o;
    return Objects.equals(this.name, patchMultilingualGlossaryParameters.name) &&
        Objects.equals(this.dictionaries, patchMultilingualGlossaryParameters.dictionaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, dictionaries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchMultilingualGlossaryParameters {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dictionaries: ").append(toIndentedString(dictionaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
