/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sets whether the translation engine should respect the original formatting, even if it would usually correct some aspects. Possible values are:  * &#x60;0&#x60; (default)  * &#x60;1&#x60;  The formatting aspects affected by this setting include:  * Punctuation at the beginning and end of the sentence  * Upper/lower case at the beginning of the sentence
 */
public enum PreserveFormattingOptionStr {
  _0("0"),
  _1("1");

  private String value;

  PreserveFormattingOptionStr(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static PreserveFormattingOptionStr fromValue(String input) {
    for (PreserveFormattingOptionStr b : PreserveFormattingOptionStr.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
