/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Language of the text to be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English  * &#x60;ES&#x60; - Spanish  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (all Portuguese varieties mixed)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;ZH&#x60; - Chinese  If this parameter is omitted, the API will attempt to detect the language of the text and translate it.
 */
public enum SourceLanguage {
  AR("AR"),
  BG("BG"),
  CS("CS"),
  DA("DA"),
  DE("DE"),
  EL("EL"),
  EN("EN"),
  ES("ES"),
  ET("ET"),
  FI("FI"),
  FR("FR"),
  HU("HU"),
  ID("ID"),
  IT("IT"),
  JA("JA"),
  KO("KO"),
  LT("LT"),
  LV("LV"),
  NB("NB"),
  NL("NL"),
  PL("PL"),
  PT("PT"),
  RO("RO"),
  RU("RU"),
  SK("SK"),
  SL("SL"),
  SV("SV"),
  TR("TR"),
  UK("UK"),
  ZH("ZH");

  private String value;

  SourceLanguage(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SourceLanguage fromValue(String input) {
    for (SourceLanguage b : SourceLanguage.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
