/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sets whether the translation engine should first split the input into sentences. For text translations where  &#x60;tag_handling&#x60; is not set to &#x60;html&#x60;, the default value is &#x60;1&#x60;, meaning the engine splits on punctuation and on newlines.  For text translations where &#x60;tag_handling&#x3D;html&#x60;, the default value is &#x60;nonewlines&#x60;, meaning the engine splits on punctuation only, ignoring newlines.    The use of &#x60;nonewlines&#x60; as the default value for text translations where &#x60;tag_handling&#x3D;html&#x60; is new behavior that was implemented in November 2022,  when HTML handling was moved out of beta.   Possible values are:    * &#x60;0&#x60; - no splitting at all, whole input is treated as one sentence  * &#x60;1&#x60; (default when &#x60;tag_handling&#x60; is not set to &#x60;html&#x60;) - splits on punctuation and on newlines  * &#x60;nonewlines&#x60; (default when &#x60;tag_handling&#x3D;html&#x60;) - splits on punctuation only, ignoring newlines  For applications that send one sentence per text parameter, we recommend setting &#x60;split_sentences&#x60; to &#x60;0&#x60;, in order to prevent the engine from splitting the sentence unintentionally.   Please note that newlines will split sentences when &#x60;split_sentences&#x3D;1&#x60;. We recommend cleaning files so they don&#x27;t contain breaking sentences or setting the parameter &#x60;split_sentences&#x60; to &#x60;nonewlines&#x60;.
 */
public enum SplitSentencesOption {
  _0("0"),
  _1("1"),
  NONEWLINES("nonewlines");

  private String value;

  SplitSentencesOption(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SplitSentencesOption fromValue(String input) {
    for (SplitSentencesOption b : SplitSentencesOption.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
