/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sets which kind of tags should be handled. Options currently available:  * &#x60;xml&#x60;: Enable XML tag handling; see [XML Handling](https://www.deepl.com/docs-api/xml).  * &#x60;html&#x60;: Enable HTML tag handling; see [HTML Handling](https://www.deepl.com/docs-api/html).
 */
public enum TagHandlingOption {
  XML("xml"),
  HTML("html");

  private String value;

  TagHandlingOption(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TagHandlingOption fromValue(String input) {
    for (TagHandlingOption b : TagHandlingOption.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
