/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sets which version of the tag handling algorithm should be used. Options currently available:  * &#x60;v2&#x60;: Improved algorithm released in October 2025 (default as of December 2025).  * &#x60;v1&#x60;: Traditional algorithm (default until December 2025).
 */
public enum TagHandlingVersionOption {
  V1("v1"),
  V2("v2");

  private String value;

  TagHandlingVersionOption(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TagHandlingVersionOption fromValue(String input) {
    for (TagHandlingVersionOption b : TagHandlingVersionOption.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
