/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The language for the text improvement. Options currently available:  * &#x60;de&#x60; - German  * &#x60;en&#x60; - English (unspecified variant, defaults to &#x60;en-US&#x60;)  * &#x60;en-GB&#x60; - English (British)  * &#x60;en-US&#x60; - English (American)  * &#x60;es&#x60; - Spanish  * &#x60;fr&#x60; - French  * &#x60;it&#x60; - Italian  * &#x60;pt&#x60; - Portuguese (unspecified variant, defaults to &#x60;pt-PT&#x60;)  * &#x60;pt-BR&#x60; - Portuguese (Brazilian)  * &#x60;pt-PT&#x60; - Portuguese (all Portuguese variants excluding Brazilian Portuguese)
 */
public enum TargetLanguageWrite {
  DE("de"),
  EN("en"),
  EN_GB("en-GB"),
  EN_US("en-US"),
  FR("fr"),
  IT("it"),
  PT("pt"),
  PT_BR("pt-BR"),
  PT_PT("pt-PT");

  private String value;

  TargetLanguageWrite(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TargetLanguageWrite fromValue(String input) {
    for (TargetLanguageWrite b : TargetLanguageWrite.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
