/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The language into which the text should be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English (unspecified variant for backward compatibility; please select &#x60;EN-GB&#x60; or &#x60;EN-US&#x60; instead)  * &#x60;EN-GB&#x60; - English (British)  * &#x60;EN-US&#x60; - English (American)  * &#x60;ES&#x60; - Spanish  * &#x60;ES-419&#x60; - Spanish (Latin American)  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (unspecified variant for backward compatibility; please select &#x60;PT-BR&#x60; or &#x60;PT-PT&#x60; instead)  * &#x60;PT-BR&#x60; - Portuguese (Brazilian)  * &#x60;PT-PT&#x60; - Portuguese (all Portuguese varieties excluding Brazilian Portuguese)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;ZH&#x60; - Chinese (unspecified variant for backward compatibility; please select &#x60;ZH-HANS&#x60; instead)  * &#x60;ZH-HANS&#x60; - Chinese (simplified)  * &#x60;ZH-HANT&#x60; - Chinese (traditional)
 */
public enum TargetLanguage {
  AR("AR"),
  BG("BG"),
  CS("CS"),
  DA("DA"),
  DE("DE"),
  EL("EL"),
  EN_GB("EN-GB"),
  EN_US("EN-US"),
  ES("ES"),
  ES_419("ES-419"),
  ET("ET"),
  FI("FI"),
  FR("FR"),
  HU("HU"),
  ID("ID"),
  IT("IT"),
  JA("JA"),
  KO("KO"),
  LT("LT"),
  LV("LV"),
  NB("NB"),
  NL("NL"),
  PL("PL"),
  PT_BR("PT-BR"),
  PT_PT("PT-PT"),
  RO("RO"),
  RU("RU"),
  SK("SK"),
  SL("SL"),
  SV("SV"),
  TR("TR"),
  UK("UK"),
  ZH("ZH"),
  ZH_HANS("ZH-HANS"),
  ZH_HANT("ZH-HANT");

  private String value;

  TargetLanguage(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TargetLanguage fromValue(String input) {
    for (TargetLanguage b : TargetLanguage.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
