/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Breakdown of character usage by category.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class UsageBreakdown {
  @JsonProperty("total_characters")
  private Integer totalCharacters = null;

  @JsonProperty("text_translation_characters")
  private Integer textTranslationCharacters = null;

  @JsonProperty("document_translation_characters")
  private Integer documentTranslationCharacters = null;

  @JsonProperty("text_improvement_characters")
  private Integer textImprovementCharacters = null;

  @JsonProperty("speech_to_text_milliseconds")
  private Integer speechToTextMilliseconds = null;

  public UsageBreakdown totalCharacters(Integer totalCharacters) {
    this.totalCharacters = totalCharacters;
    return this;
  }

   /**
   * Total number of characters used.
   * @return totalCharacters
  **/
  public Integer getTotalCharacters() {
    return totalCharacters;
  }

  public void setTotalCharacters(Integer totalCharacters) {
    this.totalCharacters = totalCharacters;
  }

  public UsageBreakdown textTranslationCharacters(Integer textTranslationCharacters) {
    this.textTranslationCharacters = textTranslationCharacters;
    return this;
  }

   /**
   * Number of characters used for text translation.
   * @return textTranslationCharacters
  **/
  public Integer getTextTranslationCharacters() {
    return textTranslationCharacters;
  }

  public void setTextTranslationCharacters(Integer textTranslationCharacters) {
    this.textTranslationCharacters = textTranslationCharacters;
  }

  public UsageBreakdown documentTranslationCharacters(Integer documentTranslationCharacters) {
    this.documentTranslationCharacters = documentTranslationCharacters;
    return this;
  }

   /**
   * Number of characters used for document translation.
   * @return documentTranslationCharacters
  **/
  public Integer getDocumentTranslationCharacters() {
    return documentTranslationCharacters;
  }

  public void setDocumentTranslationCharacters(Integer documentTranslationCharacters) {
    this.documentTranslationCharacters = documentTranslationCharacters;
  }

  public UsageBreakdown textImprovementCharacters(Integer textImprovementCharacters) {
    this.textImprovementCharacters = textImprovementCharacters;
    return this;
  }

   /**
   * Number of characters used for text improvement.
   * @return textImprovementCharacters
  **/
  public Integer getTextImprovementCharacters() {
    return textImprovementCharacters;
  }

  public void setTextImprovementCharacters(Integer textImprovementCharacters) {
    this.textImprovementCharacters = textImprovementCharacters;
  }

  public UsageBreakdown speechToTextMilliseconds(Integer speechToTextMilliseconds) {
    this.speechToTextMilliseconds = speechToTextMilliseconds;
    return this;
  }

   /**
   * Duration of speech-to-text usage in milliseconds.
   * @return speechToTextMilliseconds
  **/
  public Integer getSpeechToTextMilliseconds() {
    return speechToTextMilliseconds;
  }

  public void setSpeechToTextMilliseconds(Integer speechToTextMilliseconds) {
    this.speechToTextMilliseconds = speechToTextMilliseconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageBreakdown usageBreakdown = (UsageBreakdown) o;
    return Objects.equals(this.totalCharacters, usageBreakdown.totalCharacters) &&
        Objects.equals(this.textTranslationCharacters, usageBreakdown.textTranslationCharacters) &&
        Objects.equals(this.documentTranslationCharacters, usageBreakdown.documentTranslationCharacters) &&
        Objects.equals(this.textImprovementCharacters, usageBreakdown.textImprovementCharacters) &&
        Objects.equals(this.speechToTextMilliseconds, usageBreakdown.speechToTextMilliseconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCharacters, textTranslationCharacters, documentTranslationCharacters, textImprovementCharacters, speechToTextMilliseconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageBreakdown {\n");
    
    sb.append("    totalCharacters: ").append(toIndentedString(totalCharacters)).append("\n");
    sb.append("    textTranslationCharacters: ").append(toIndentedString(textTranslationCharacters)).append("\n");
    sb.append("    documentTranslationCharacters: ").append(toIndentedString(documentTranslationCharacters)).append("\n");
    sb.append("    textImprovementCharacters: ").append(toIndentedString(textImprovementCharacters)).append("\n");
    sb.append("    speechToTextMilliseconds: ").append(toIndentedString(speechToTextMilliseconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
