/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsageResponseProducts
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class UsageResponseProducts {
  @JsonProperty("product_type")
  private String productType = null;

  /**
   * The billing unit for this product type.
   */
  public enum BillingUnitEnum {
    CHARACTERS("characters"),
    MILLISECONDS("milliseconds");

    private String value;

    BillingUnitEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static BillingUnitEnum fromValue(String input) {
      for (BillingUnitEnum b : BillingUnitEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("billing_unit")
  private BillingUnitEnum billingUnit = null;

  @JsonProperty("api_key_unit_count")
  private Integer apiKeyUnitCount = null;

  @JsonProperty("account_unit_count")
  private Integer accountUnitCount = null;

  @JsonProperty("api_key_character_count")
  private Integer apiKeyCharacterCount = null;

  @JsonProperty("character_count")
  private Integer characterCount = null;

  public UsageResponseProducts productType(String productType) {
    this.productType = productType;
    return this;
  }

   /**
   * The type of product (e.g., &#x27;write&#x27;, &#x27;translate&#x27;).
   * @return productType
  **/
  public String getProductType() {
    return productType;
  }

  public void setProductType(String productType) {
    this.productType = productType;
  }

  public UsageResponseProducts billingUnit(BillingUnitEnum billingUnit) {
    this.billingUnit = billingUnit;
    return this;
  }

   /**
   * The billing unit for this product type.
   * @return billingUnit
  **/
  public BillingUnitEnum getBillingUnit() {
    return billingUnit;
  }

  public void setBillingUnit(BillingUnitEnum billingUnit) {
    this.billingUnit = billingUnit;
  }

  public UsageResponseProducts apiKeyUnitCount(Integer apiKeyUnitCount) {
    this.apiKeyUnitCount = apiKeyUnitCount;
    return this;
  }

   /**
   * Units used for this product by this API key in the current period.
   * @return apiKeyUnitCount
  **/
  public Integer getApiKeyUnitCount() {
    return apiKeyUnitCount;
  }

  public void setApiKeyUnitCount(Integer apiKeyUnitCount) {
    this.apiKeyUnitCount = apiKeyUnitCount;
  }

  public UsageResponseProducts accountUnitCount(Integer accountUnitCount) {
    this.accountUnitCount = accountUnitCount;
    return this;
  }

   /**
   * Total units used for this product by the account in the current period.
   * @return accountUnitCount
  **/
  public Integer getAccountUnitCount() {
    return accountUnitCount;
  }

  public void setAccountUnitCount(Integer accountUnitCount) {
    this.accountUnitCount = accountUnitCount;
  }

  public UsageResponseProducts apiKeyCharacterCount(Integer apiKeyCharacterCount) {
    this.apiKeyCharacterCount = apiKeyCharacterCount;
    return this;
  }

   /**
   * Characters used for this product by this API key in the current period.
   * @return apiKeyCharacterCount
  **/
  public Integer getApiKeyCharacterCount() {
    return apiKeyCharacterCount;
  }

  public void setApiKeyCharacterCount(Integer apiKeyCharacterCount) {
    this.apiKeyCharacterCount = apiKeyCharacterCount;
  }

  public UsageResponseProducts characterCount(Integer characterCount) {
    this.characterCount = characterCount;
    return this;
  }

   /**
   * Total characters used for this product in the current period.
   * @return characterCount
  **/
  public Integer getCharacterCount() {
    return characterCount;
  }

  public void setCharacterCount(Integer characterCount) {
    this.characterCount = characterCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageResponseProducts usageResponseProducts = (UsageResponseProducts) o;
    return Objects.equals(this.productType, usageResponseProducts.productType) &&
        Objects.equals(this.billingUnit, usageResponseProducts.billingUnit) &&
        Objects.equals(this.apiKeyUnitCount, usageResponseProducts.apiKeyUnitCount) &&
        Objects.equals(this.accountUnitCount, usageResponseProducts.accountUnitCount) &&
        Objects.equals(this.apiKeyCharacterCount, usageResponseProducts.apiKeyCharacterCount) &&
        Objects.equals(this.characterCount, usageResponseProducts.characterCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productType, billingUnit, apiKeyUnitCount, accountUnitCount, apiKeyCharacterCount, characterCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageResponseProducts {\n");
    
    sb.append("    productType: ").append(toIndentedString(productType)).append("\n");
    sb.append("    billingUnit: ").append(toIndentedString(billingUnit)).append("\n");
    sb.append("    apiKeyUnitCount: ").append(toIndentedString(apiKeyUnitCount)).append("\n");
    sb.append("    accountUnitCount: ").append(toIndentedString(accountUnitCount)).append("\n");
    sb.append("    apiKeyCharacterCount: ").append(toIndentedString(apiKeyCharacterCount)).append("\n");
    sb.append("    characterCount: ").append(toIndentedString(characterCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
