/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.File;
/**
 * V2DocumentBody
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class V2DocumentBody {
  /**
   * Language of the text to be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English  * &#x60;ES&#x60; - Spanish  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (all Portuguese varieties mixed)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;ZH&#x60; - Chinese  If this parameter is omitted, the API will attempt to detect the language of the text and translate it.
   */
  public enum SourceLangEnum {
    AR("AR"),
    BG("BG"),
    CS("CS"),
    DA("DA"),
    DE("DE"),
    EL("EL"),
    EN("EN"),
    ES("ES"),
    ET("ET"),
    FI("FI"),
    FR("FR"),
    HU("HU"),
    ID("ID"),
    IT("IT"),
    JA("JA"),
    KO("KO"),
    LT("LT"),
    LV("LV"),
    NB("NB"),
    NL("NL"),
    PL("PL"),
    PT("PT"),
    RO("RO"),
    RU("RU"),
    SK("SK"),
    SL("SL"),
    SV("SV"),
    TR("TR"),
    UK("UK"),
    ZH("ZH");

    private String value;

    SourceLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceLangEnum fromValue(String input) {
      for (SourceLangEnum b : SourceLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_lang")
  private SourceLangEnum sourceLang = null;

  /**
   * The language into which the text should be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English (unspecified variant for backward compatibility; please select &#x60;EN-GB&#x60; or &#x60;EN-US&#x60; instead)  * &#x60;EN-GB&#x60; - English (British)  * &#x60;EN-US&#x60; - English (American)  * &#x60;ES&#x60; - Spanish  * &#x60;ES-419&#x60; - Spanish (Latin American)  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (unspecified variant for backward compatibility; please select &#x60;PT-BR&#x60; or &#x60;PT-PT&#x60; instead)  * &#x60;PT-BR&#x60; - Portuguese (Brazilian)  * &#x60;PT-PT&#x60; - Portuguese (all Portuguese varieties excluding Brazilian Portuguese)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;ZH&#x60; - Chinese (unspecified variant for backward compatibility; please select &#x60;ZH-HANS&#x60; instead)  * &#x60;ZH-HANS&#x60; - Chinese (simplified)  * &#x60;ZH-HANT&#x60; - Chinese (traditional)
   */
  public enum TargetLangEnum {
    AR("AR"),
    BG("BG"),
    CS("CS"),
    DA("DA"),
    DE("DE"),
    EL("EL"),
    EN_GB("EN-GB"),
    EN_US("EN-US"),
    ES("ES"),
    ES_419("ES-419"),
    ET("ET"),
    FI("FI"),
    FR("FR"),
    HU("HU"),
    ID("ID"),
    IT("IT"),
    JA("JA"),
    KO("KO"),
    LT("LT"),
    LV("LV"),
    NB("NB"),
    NL("NL"),
    PL("PL"),
    PT_BR("PT-BR"),
    PT_PT("PT-PT"),
    RO("RO"),
    RU("RU"),
    SK("SK"),
    SL("SL"),
    SV("SV"),
    TR("TR"),
    UK("UK"),
    ZH("ZH"),
    ZH_HANS("ZH-HANS"),
    ZH_HANT("ZH-HANT");

    private String value;

    TargetLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TargetLangEnum fromValue(String input) {
      for (TargetLangEnum b : TargetLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("target_lang")
  private TargetLangEnum targetLang = null;

  @JsonProperty("file")
  private File file = null;

  @JsonProperty("filename")
  private String filename = null;

  @JsonProperty("output_format")
  private String outputFormat = null;

  /**
   * Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages &#x60;DE&#x60; (German), &#x60;FR&#x60; (French), &#x60;IT&#x60; (Italian), &#x60;ES&#x60; (Spanish), &#x60;ES-419&#x60; (Latin American Spanish), &#x60;NL&#x60; (Dutch), &#x60;PL&#x60; (Polish), &#x60;PT-BR&#x60; and &#x60;PT-PT&#x60; (Portuguese), &#x60;JA&#x60; (Japanese), and &#x60;RU&#x60; (Russian). Learn more about the plain/polite feature for Japanese [here](https://support.deepl.com/hc/en-us/articles/6306700061852-About-the-plain-polite-feature-in-Japanese). Setting this parameter with a target language that does not support formality will fail, unless one of the &#x60;prefer_...&#x60; options are used. Possible options are:   * &#x60;default&#x60; (default)   * &#x60;more&#x60; - for a more formal language   * &#x60;less&#x60; - for a more informal language   * &#x60;prefer_more&#x60; - for a more formal language if available, otherwise fallback to default formality   * &#x60;prefer_less&#x60; - for a more informal language if available, otherwise fallback to default formality
   */
  public enum FormalityEnum {
    DEFAULT("default"),
    MORE("more"),
    LESS("less"),
    PREFER_MORE("prefer_more"),
    PREFER_LESS("prefer_less");

    private String value;

    FormalityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FormalityEnum fromValue(String input) {
      for (FormalityEnum b : FormalityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("formality")
  private FormalityEnum formality = FormalityEnum.DEFAULT;

  @JsonProperty("glossary_id")
  private String glossaryId = null;

  public V2DocumentBody sourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
    return this;
  }

   /**
   * Language of the text to be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English  * &#x60;ES&#x60; - Spanish  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (all Portuguese varieties mixed)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;ZH&#x60; - Chinese  If this parameter is omitted, the API will attempt to detect the language of the text and translate it.
   * @return sourceLang
  **/
  public SourceLangEnum getSourceLang() {
    return sourceLang;
  }

  public void setSourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
  }

  public V2DocumentBody targetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
    return this;
  }

   /**
   * The language into which the text should be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English (unspecified variant for backward compatibility; please select &#x60;EN-GB&#x60; or &#x60;EN-US&#x60; instead)  * &#x60;EN-GB&#x60; - English (British)  * &#x60;EN-US&#x60; - English (American)  * &#x60;ES&#x60; - Spanish  * &#x60;ES-419&#x60; - Spanish (Latin American)  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (unspecified variant for backward compatibility; please select &#x60;PT-BR&#x60; or &#x60;PT-PT&#x60; instead)  * &#x60;PT-BR&#x60; - Portuguese (Brazilian)  * &#x60;PT-PT&#x60; - Portuguese (all Portuguese varieties excluding Brazilian Portuguese)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;ZH&#x60; - Chinese (unspecified variant for backward compatibility; please select &#x60;ZH-HANS&#x60; instead)  * &#x60;ZH-HANS&#x60; - Chinese (simplified)  * &#x60;ZH-HANT&#x60; - Chinese (traditional)
   * @return targetLang
  **/
  public TargetLangEnum getTargetLang() {
    return targetLang;
  }

  public void setTargetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
  }

  public V2DocumentBody file(File file) {
    this.file = file;
    return this;
  }

   /**
   * The document file to be translated. The file name should be included in this part&#x27;s content disposition. As an alternative, the filename parameter can be used. The following file types and extensions are supported:   * &#x60;docx&#x60; - Microsoft Word Document   * &#x60;pptx&#x60; - Microsoft PowerPoint Document   * &#x60;xlsx&#x60; - Microsoft Excel Document   * &#x60;pdf&#x60; - Portable Document Format   * &#x60;htm / html&#x60; - HTML Document   * &#x60;txt&#x60; - Plain Text Document   * &#x60;xlf / xliff&#x60; - XLIFF Document, version 2.1   * &#x60;srt&#x60; - SRT Document
   * @return file
  **/
  public File getFile() {
    return file;
  }

  public void setFile(File file) {
    this.file = file;
  }

  public V2DocumentBody filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * The name of the uploaded file. Can be used as an alternative to including the file name in the file part&#x27;s content disposition.
   * @return filename
  **/
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public V2DocumentBody outputFormat(String outputFormat) {
    this.outputFormat = outputFormat;
    return this;
  }

   /**
   * File extension of desired format of translated file, for example: &#x60;docx&#x60;. If unspecified, by default the translated file will be in the same format as the input file.  Note: Not all combinations of input file and translation file extensions are permitted. See [Document Format Conversions](https://www.deepl.com/docs-api/documents/format-conversions) for the permitted combinations.
   * @return outputFormat
  **/
  public String getOutputFormat() {
    return outputFormat;
  }

  public void setOutputFormat(String outputFormat) {
    this.outputFormat = outputFormat;
  }

  public V2DocumentBody formality(FormalityEnum formality) {
    this.formality = formality;
    return this;
  }

   /**
   * Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages &#x60;DE&#x60; (German), &#x60;FR&#x60; (French), &#x60;IT&#x60; (Italian), &#x60;ES&#x60; (Spanish), &#x60;ES-419&#x60; (Latin American Spanish), &#x60;NL&#x60; (Dutch), &#x60;PL&#x60; (Polish), &#x60;PT-BR&#x60; and &#x60;PT-PT&#x60; (Portuguese), &#x60;JA&#x60; (Japanese), and &#x60;RU&#x60; (Russian). Learn more about the plain/polite feature for Japanese [here](https://support.deepl.com/hc/en-us/articles/6306700061852-About-the-plain-polite-feature-in-Japanese). Setting this parameter with a target language that does not support formality will fail, unless one of the &#x60;prefer_...&#x60; options are used. Possible options are:   * &#x60;default&#x60; (default)   * &#x60;more&#x60; - for a more formal language   * &#x60;less&#x60; - for a more informal language   * &#x60;prefer_more&#x60; - for a more formal language if available, otherwise fallback to default formality   * &#x60;prefer_less&#x60; - for a more informal language if available, otherwise fallback to default formality
   * @return formality
  **/
  public FormalityEnum getFormality() {
    return formality;
  }

  public void setFormality(FormalityEnum formality) {
    this.formality = formality;
  }

  public V2DocumentBody glossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
    return this;
  }

   /**
   * A unique ID assigned to a glossary.
   * @return glossaryId
  **/
  public String getGlossaryId() {
    return glossaryId;
  }

  public void setGlossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2DocumentBody v2DocumentBody = (V2DocumentBody) o;
    return Objects.equals(this.sourceLang, v2DocumentBody.sourceLang) &&
        Objects.equals(this.targetLang, v2DocumentBody.targetLang) &&
        Objects.equals(this.file, v2DocumentBody.file) &&
        Objects.equals(this.filename, v2DocumentBody.filename) &&
        Objects.equals(this.outputFormat, v2DocumentBody.outputFormat) &&
        Objects.equals(this.formality, v2DocumentBody.formality) &&
        Objects.equals(this.glossaryId, v2DocumentBody.glossaryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceLang, targetLang, Objects.hashCode(file), filename, outputFormat, formality, glossaryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2DocumentBody {\n");
    
    sb.append("    sourceLang: ").append(toIndentedString(sourceLang)).append("\n");
    sb.append("    targetLang: ").append(toIndentedString(targetLang)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    outputFormat: ").append(toIndentedString(outputFormat)).append("\n");
    sb.append("    formality: ").append(toIndentedString(formality)).append("\n");
    sb.append("    glossaryId: ").append(toIndentedString(glossaryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
