/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * V2TranslateBody1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class V2TranslateBody1 {
  @JsonProperty("text")
  private List<String> text = new ArrayList<>();

  /**
   * Language of the text to be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English  * &#x60;ES&#x60; - Spanish  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HE&#x60; - Hebrew  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (all Portuguese varieties mixed)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TH&#x60; - Thai  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;VI&#x60; - Vietnamese  * &#x60;ZH&#x60; - Chinese  If this parameter is omitted, the API will attempt to detect the language of the text and translate it.
   */
  public enum SourceLangEnum {
    AR("AR"),
    BG("BG"),
    CS("CS"),
    DA("DA"),
    DE("DE"),
    EL("EL"),
    EN("EN"),
    ES("ES"),
    ET("ET"),
    FI("FI"),
    FR("FR"),
    HE("HE"),
    HU("HU"),
    ID("ID"),
    IT("IT"),
    JA("JA"),
    KO("KO"),
    LT("LT"),
    LV("LV"),
    NB("NB"),
    NL("NL"),
    PL("PL"),
    PT("PT"),
    RO("RO"),
    RU("RU"),
    SK("SK"),
    SL("SL"),
    SV("SV"),
    TH("TH"),
    TR("TR"),
    UK("UK"),
    VI("VI"),
    ZH("ZH");

    private String value;

    SourceLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceLangEnum fromValue(String input) {
      for (SourceLangEnum b : SourceLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_lang")
  private SourceLangEnum sourceLang = null;

  /**
   * The language into which the text should be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English (unspecified variant for backward compatibility; please select &#x60;EN-GB&#x60; or &#x60;EN-US&#x60; instead)  * &#x60;EN-GB&#x60; - English (British)  * &#x60;EN-US&#x60; - English (American)  * &#x60;ES&#x60; - Spanish  * &#x60;ES-419&#x60; - Spanish (Latin American)  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HE&#x60; - Hebrew  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (unspecified variant for backward compatibility; please select &#x60;PT-BR&#x60; or &#x60;PT-PT&#x60; instead)  * &#x60;PT-BR&#x60; - Portuguese (Brazilian)  * &#x60;PT-PT&#x60; - Portuguese (all Portuguese variants excluding Brazilian Portuguese)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TH&#x60; - Thai  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;VI&#x60; - Vietnamese  * &#x60;ZH&#x60; - Chinese (unspecified variant for backward compatibility; please select &#x60;ZH-HANS&#x60; or &#x60;ZH-HANT&#x60; instead)  * &#x60;ZH-HANS&#x60; - Chinese (simplified)  * &#x60;ZH-HANT&#x60; - Chinese (traditional)
   */
  public enum TargetLangEnum {
    AR("AR"),
    BG("BG"),
    CS("CS"),
    DA("DA"),
    DE("DE"),
    EL("EL"),
    EN_GB("EN-GB"),
    EN_US("EN-US"),
    ES("ES"),
    ES_419("ES-419"),
    ET("ET"),
    FI("FI"),
    FR("FR"),
    HE("HE"),
    HU("HU"),
    ID("ID"),
    IT("IT"),
    JA("JA"),
    KO("KO"),
    LT("LT"),
    LV("LV"),
    NB("NB"),
    NL("NL"),
    PL("PL"),
    PT_BR("PT-BR"),
    PT_PT("PT-PT"),
    RO("RO"),
    RU("RU"),
    SK("SK"),
    SL("SL"),
    SV("SV"),
    TH("TH"),
    TR("TR"),
    UK("UK"),
    VI("VI"),
    ZH("ZH"),
    ZH_HANS("ZH-HANS"),
    ZH_HANT("ZH-HANT");

    private String value;

    TargetLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TargetLangEnum fromValue(String input) {
      for (TargetLangEnum b : TargetLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("target_lang")
  private TargetLangEnum targetLang = null;

  @JsonProperty("context")
  private String context = null;

  @JsonProperty("show_billed_characters")
  private Boolean showBilledCharacters = null;

  /**
   * Sets whether the translation engine should first split the input into sentences. For text translations where  &#x60;tag_handling&#x60; is not set to &#x60;html&#x60;, the default value is &#x60;1&#x60;, meaning the engine splits on punctuation and on newlines.  For text translations where &#x60;tag_handling&#x3D;html&#x60;, the default value is &#x60;nonewlines&#x60;, meaning the engine splits on punctuation only, ignoring newlines.    The use of &#x60;nonewlines&#x60; as the default value for text translations where &#x60;tag_handling&#x3D;html&#x60; is new behavior that was implemented in November 2022,  when HTML handling was moved out of beta.   Possible values are:    * &#x60;0&#x60; - no splitting at all, whole input is treated as one sentence  * &#x60;1&#x60; (default when &#x60;tag_handling&#x60; is not set to &#x60;html&#x60;) - splits on punctuation and on newlines  * &#x60;nonewlines&#x60; (default when &#x60;tag_handling&#x3D;html&#x60;) - splits on punctuation only, ignoring newlines  For applications that send one sentence per text parameter, we recommend setting &#x60;split_sentences&#x60; to &#x60;0&#x60;, in order to prevent the engine from splitting the sentence unintentionally.   Please note that newlines will split sentences when &#x60;split_sentences&#x3D;1&#x60;. We recommend cleaning files so they don&#x27;t contain breaking sentences or setting the parameter &#x60;split_sentences&#x60; to &#x60;nonewlines&#x60;.
   */
  public enum SplitSentencesEnum {
    _0("0"),
    _1("1"),
    NONEWLINES("nonewlines");

    private String value;

    SplitSentencesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SplitSentencesEnum fromValue(String input) {
      for (SplitSentencesEnum b : SplitSentencesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("split_sentences")
  private SplitSentencesEnum splitSentences = SplitSentencesEnum._1;

  /**
   * Sets whether the translation engine should respect the original formatting, even if it would usually correct some aspects. Possible values are:  * &#x60;0&#x60; (default)  * &#x60;1&#x60;  The formatting aspects affected by this setting include:  * Punctuation at the beginning and end of the sentence  * Upper/lower case at the beginning of the sentence
   */
  public enum PreserveFormattingEnum {
    _0("0"),
    _1("1");

    private String value;

    PreserveFormattingEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PreserveFormattingEnum fromValue(String input) {
      for (PreserveFormattingEnum b : PreserveFormattingEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("preserve_formatting")
  private PreserveFormattingEnum preserveFormatting = PreserveFormattingEnum._0;

  /**
   * Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages &#x60;DE&#x60; (German), &#x60;FR&#x60; (French), &#x60;IT&#x60; (Italian), &#x60;ES&#x60; (Spanish), &#x60;ES-419&#x60; (Latin American Spanish), &#x60;NL&#x60; (Dutch), &#x60;PL&#x60; (Polish), &#x60;PT-BR&#x60; and &#x60;PT-PT&#x60; (Portuguese), &#x60;JA&#x60; (Japanese), and &#x60;RU&#x60; (Russian). Learn more about the plain/polite feature for Japanese [here](https://support.deepl.com/hc/en-us/articles/6306700061852-About-the-plain-polite-feature-in-Japanese). Setting this parameter with a target language that does not support formality will fail, unless one of the &#x60;prefer_...&#x60; options are used. Possible options are:   * &#x60;default&#x60; (default)   * &#x60;more&#x60; - for a more formal language   * &#x60;less&#x60; - for a more informal language   * &#x60;prefer_more&#x60; - for a more formal language if available, otherwise fallback to default formality   * &#x60;prefer_less&#x60; - for a more informal language if available, otherwise fallback to default formality
   */
  public enum FormalityEnum {
    DEFAULT("default"),
    MORE("more"),
    LESS("less"),
    PREFER_MORE("prefer_more"),
    PREFER_LESS("prefer_less");

    private String value;

    FormalityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FormalityEnum fromValue(String input) {
      for (FormalityEnum b : FormalityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("formality")
  private FormalityEnum formality = FormalityEnum.DEFAULT;

  /**
   * Specifies which DeepL model should be used for translation.  Possible values are: * &#x60;latency_optimized&#x60; (default) - uses lower latency “classic” translation models, which support all language pairs;   default value * &#x60;quality_optimized&#x60; - uses higher latency, improved quality “next-gen” translation models, which support only a   subset of language pairs; if a language pair that is not supported by next-gen models is included in the   request, it will fail. Consider using prefer_quality_optimized instead. * &#x60;prefer_quality_optimized&#x60; - prioritizes use of higher latency, improved quality “next-gen” translation models,   which support only a subset of DeepL languages; if a request includes a language pair not supported by   next-gen models, the request will fall back to latency_optimized classic models.
   */
  public enum ModelTypeEnum {
    QUALITY_OPTIMIZED("quality_optimized"),
    PREFER_QUALITY_OPTIMIZED("prefer_quality_optimized"),
    LATENCY_OPTIMIZED("latency_optimized");

    private String value;

    ModelTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ModelTypeEnum fromValue(String input) {
      for (ModelTypeEnum b : ModelTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("model_type")
  private ModelTypeEnum modelType = null;

  @JsonProperty("glossary_id")
  private String glossaryId = null;

  /**
   * Sets which kind of tags should be handled. Options currently available:  * &#x60;xml&#x60;: Enable XML tag handling; see [XML Handling](https://www.deepl.com/docs-api/xml).  * &#x60;html&#x60;: Enable HTML tag handling; see [HTML Handling](https://www.deepl.com/docs-api/html).
   */
  public enum TagHandlingEnum {
    XML("xml"),
    HTML("html");

    private String value;

    TagHandlingEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TagHandlingEnum fromValue(String input) {
      for (TagHandlingEnum b : TagHandlingEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("tag_handling")
  private TagHandlingEnum tagHandling = null;

  /**
   * Sets which version of the tag handling algorithm should be used. Options currently available:  * &#x60;v2&#x60;: Improved algorithm released in October 2025 (default as of December 2025).  * &#x60;v1&#x60;: Traditional algorithm (default until December 2025).
   */
  public enum TagHandlingVersionEnum {
    V1("v1"),
    V2("v2");

    private String value;

    TagHandlingVersionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TagHandlingVersionEnum fromValue(String input) {
      for (TagHandlingVersionEnum b : TagHandlingVersionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("tag_handling_version")
  private TagHandlingVersionEnum tagHandlingVersion = null;

  /**
   * The automatic detection of the XML structure won&#x27;t yield best results in all XML files. You can disable this automatic mechanism altogether by setting the &#x60;outline_detection&#x60; parameter to &#x60;0&#x60; and selecting the tags that should be considered structure tags. This will split sentences using the &#x60;splitting_tags&#x60; parameter.   In the example below, we achieve the same results as the automatic engine by disabling automatic detection with &#x60;outline_detection&#x3D;0&#x60; and setting the parameters manually to &#x60;tag_handling&#x3D;xml&#x60;, &#x60;split_sentences&#x3D;nonewlines&#x60;,  and &#x60;splitting_tags&#x3D;par,title&#x60;.  * Example request:    &#x60;&#x60;&#x60;    &lt;document&gt;      &lt;meta&gt;        &lt;title&gt;A document&#x27;s title&lt;/title&gt;      &lt;/meta&gt;      &lt;content&gt;        &lt;par&gt;This is the first sentence. Followed by a second one.&lt;/par&gt;        &lt;par&gt;This is the third sentence.&lt;/par&gt;      &lt;/content&gt;    &lt;/document&gt;    &#x60;&#x60;&#x60;  * Example response:    &#x60;&#x60;&#x60;    &lt;document&gt;      &lt;meta&gt;        &lt;title&gt;Der Titel eines Dokuments&lt;/title&gt;      &lt;/meta&gt;      &lt;content&gt;        &lt;par&gt;Das ist der erste Satz. Gefolgt von einem zweiten.&lt;/par&gt;        &lt;par&gt;Dies ist der dritte Satz.&lt;/par&gt;      &lt;/content&gt;    &lt;/document&gt;    &#x60;&#x60;&#x60; While this approach is slightly more complicated, it allows for greater control over the structure of the translation output.
   */
  public enum OutlineDetectionEnum {
    _0("0");

    private String value;

    OutlineDetectionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static OutlineDetectionEnum fromValue(String input) {
      for (OutlineDetectionEnum b : OutlineDetectionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("outline_detection")
  private OutlineDetectionEnum outlineDetection = null;

  @JsonProperty("non_splitting_tags")
  private String nonSplittingTags = null;

  @JsonProperty("splitting_tags")
  private String splittingTags = null;

  @JsonProperty("ignore_tags")
  private String ignoreTags = null;

  public V2TranslateBody1 text(List<String> text) {
    this.text = text;
    return this;
  }

  public V2TranslateBody1 addTextItem(String textItem) {
    this.text.add(textItem);
    return this;
  }

   /**
   * Text to be translated. Only UTF-8-encoded plain text is supported. The parameter may be specified multiple times and translations are returned in the same order as they are requested. Each of the parameter values may contain multiple sentences.
   * @return text
  **/
  public List<String> getText() {
    return text;
  }

  public void setText(List<String> text) {
    this.text = text;
  }

  public V2TranslateBody1 sourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
    return this;
  }

   /**
   * Language of the text to be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English  * &#x60;ES&#x60; - Spanish  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HE&#x60; - Hebrew  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (all Portuguese varieties mixed)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TH&#x60; - Thai  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;VI&#x60; - Vietnamese  * &#x60;ZH&#x60; - Chinese  If this parameter is omitted, the API will attempt to detect the language of the text and translate it.
   * @return sourceLang
  **/
  public SourceLangEnum getSourceLang() {
    return sourceLang;
  }

  public void setSourceLang(SourceLangEnum sourceLang) {
    this.sourceLang = sourceLang;
  }

  public V2TranslateBody1 targetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
    return this;
  }

   /**
   * The language into which the text should be translated. Options currently available:  * &#x60;AR&#x60; - Arabic  * &#x60;BG&#x60; - Bulgarian  * &#x60;CS&#x60; - Czech  * &#x60;DA&#x60; - Danish  * &#x60;DE&#x60; - German  * &#x60;EL&#x60; - Greek  * &#x60;EN&#x60; - English (unspecified variant for backward compatibility; please select &#x60;EN-GB&#x60; or &#x60;EN-US&#x60; instead)  * &#x60;EN-GB&#x60; - English (British)  * &#x60;EN-US&#x60; - English (American)  * &#x60;ES&#x60; - Spanish  * &#x60;ES-419&#x60; - Spanish (Latin American)  * &#x60;ET&#x60; - Estonian  * &#x60;FI&#x60; - Finnish  * &#x60;FR&#x60; - French  * &#x60;HE&#x60; - Hebrew  * &#x60;HU&#x60; - Hungarian  * &#x60;ID&#x60; - Indonesian  * &#x60;IT&#x60; - Italian  * &#x60;JA&#x60; - Japanese  * &#x60;KO&#x60; - Korean  * &#x60;LT&#x60; - Lithuanian  * &#x60;LV&#x60; - Latvian  * &#x60;NB&#x60; - Norwegian (Bokmål)  * &#x60;NL&#x60; - Dutch  * &#x60;PL&#x60; - Polish  * &#x60;PT&#x60; - Portuguese (unspecified variant for backward compatibility; please select &#x60;PT-BR&#x60; or &#x60;PT-PT&#x60; instead)  * &#x60;PT-BR&#x60; - Portuguese (Brazilian)  * &#x60;PT-PT&#x60; - Portuguese (all Portuguese variants excluding Brazilian Portuguese)  * &#x60;RO&#x60; - Romanian  * &#x60;RU&#x60; - Russian  * &#x60;SK&#x60; - Slovak  * &#x60;SL&#x60; - Slovenian  * &#x60;SV&#x60; - Swedish  * &#x60;TH&#x60; - Thai  * &#x60;TR&#x60; - Turkish  * &#x60;UK&#x60; - Ukrainian  * &#x60;VI&#x60; - Vietnamese  * &#x60;ZH&#x60; - Chinese (unspecified variant for backward compatibility; please select &#x60;ZH-HANS&#x60; or &#x60;ZH-HANT&#x60; instead)  * &#x60;ZH-HANS&#x60; - Chinese (simplified)  * &#x60;ZH-HANT&#x60; - Chinese (traditional)
   * @return targetLang
  **/
  public TargetLangEnum getTargetLang() {
    return targetLang;
  }

  public void setTargetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
  }

  public V2TranslateBody1 context(String context) {
    this.context = context;
    return this;
  }

   /**
   * The &#x60;context&#x60; parameter makes it possible to include additional context that can influence a translation but is not translated itself.  This additional context can potentially improve translation quality when translating short, low-context source texts such  as product names on an e-commerce website, article headlines on a news website, or UI elements.   For example...   - When translating a product name, you might pass the product description as context.    - When translating a news article headline, you might pass the first few sentences or a summary of the article as context.   For best results, we recommend sending a few complete sentences of context in the same language as the source text.  There is no size limit for the &#x60;context&#x60; parameter itself, but the request body size limit of 128 KiB still applies to  all text translation requests.    If you send a request with multiple &#x60;text&#x60; parameters, the &#x60;context&#x60; parameter will be applied to each one.    Characters included in the &#x60;context&#x60; parameter will not be counted toward billing (i.e. there is no additional  cost for using the &#x60;context&#x60; parameter, and only characters sent in the text parameter(s) will be counted toward  billing for text translation even when the &#x60;context&#x60; parameter is included in a request).
   * @return context
  **/
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public V2TranslateBody1 showBilledCharacters(Boolean showBilledCharacters) {
    this.showBilledCharacters = showBilledCharacters;
    return this;
  }

   /**
   * When true, the response will include the billed_characters parameter, giving the  number of characters from the request that will be counted by DeepL for billing purposes.  Note: for requests sent as URL-encoded forms, boolean values should be specified as \&quot;1\&quot; or \&quot;0\&quot;.
   * @return showBilledCharacters
  **/
  public Boolean isShowBilledCharacters() {
    return showBilledCharacters;
  }

  public void setShowBilledCharacters(Boolean showBilledCharacters) {
    this.showBilledCharacters = showBilledCharacters;
  }

  public V2TranslateBody1 splitSentences(SplitSentencesEnum splitSentences) {
    this.splitSentences = splitSentences;
    return this;
  }

   /**
   * Sets whether the translation engine should first split the input into sentences. For text translations where  &#x60;tag_handling&#x60; is not set to &#x60;html&#x60;, the default value is &#x60;1&#x60;, meaning the engine splits on punctuation and on newlines.  For text translations where &#x60;tag_handling&#x3D;html&#x60;, the default value is &#x60;nonewlines&#x60;, meaning the engine splits on punctuation only, ignoring newlines.    The use of &#x60;nonewlines&#x60; as the default value for text translations where &#x60;tag_handling&#x3D;html&#x60; is new behavior that was implemented in November 2022,  when HTML handling was moved out of beta.   Possible values are:    * &#x60;0&#x60; - no splitting at all, whole input is treated as one sentence  * &#x60;1&#x60; (default when &#x60;tag_handling&#x60; is not set to &#x60;html&#x60;) - splits on punctuation and on newlines  * &#x60;nonewlines&#x60; (default when &#x60;tag_handling&#x3D;html&#x60;) - splits on punctuation only, ignoring newlines  For applications that send one sentence per text parameter, we recommend setting &#x60;split_sentences&#x60; to &#x60;0&#x60;, in order to prevent the engine from splitting the sentence unintentionally.   Please note that newlines will split sentences when &#x60;split_sentences&#x3D;1&#x60;. We recommend cleaning files so they don&#x27;t contain breaking sentences or setting the parameter &#x60;split_sentences&#x60; to &#x60;nonewlines&#x60;.
   * @return splitSentences
  **/
  public SplitSentencesEnum getSplitSentences() {
    return splitSentences;
  }

  public void setSplitSentences(SplitSentencesEnum splitSentences) {
    this.splitSentences = splitSentences;
  }

  public V2TranslateBody1 preserveFormatting(PreserveFormattingEnum preserveFormatting) {
    this.preserveFormatting = preserveFormatting;
    return this;
  }

   /**
   * Sets whether the translation engine should respect the original formatting, even if it would usually correct some aspects. Possible values are:  * &#x60;0&#x60; (default)  * &#x60;1&#x60;  The formatting aspects affected by this setting include:  * Punctuation at the beginning and end of the sentence  * Upper/lower case at the beginning of the sentence
   * @return preserveFormatting
  **/
  public PreserveFormattingEnum getPreserveFormatting() {
    return preserveFormatting;
  }

  public void setPreserveFormatting(PreserveFormattingEnum preserveFormatting) {
    this.preserveFormatting = preserveFormatting;
  }

  public V2TranslateBody1 formality(FormalityEnum formality) {
    this.formality = formality;
    return this;
  }

   /**
   * Sets whether the translated text should lean towards formal or informal language. This feature currently only works for target languages &#x60;DE&#x60; (German), &#x60;FR&#x60; (French), &#x60;IT&#x60; (Italian), &#x60;ES&#x60; (Spanish), &#x60;ES-419&#x60; (Latin American Spanish), &#x60;NL&#x60; (Dutch), &#x60;PL&#x60; (Polish), &#x60;PT-BR&#x60; and &#x60;PT-PT&#x60; (Portuguese), &#x60;JA&#x60; (Japanese), and &#x60;RU&#x60; (Russian). Learn more about the plain/polite feature for Japanese [here](https://support.deepl.com/hc/en-us/articles/6306700061852-About-the-plain-polite-feature-in-Japanese). Setting this parameter with a target language that does not support formality will fail, unless one of the &#x60;prefer_...&#x60; options are used. Possible options are:   * &#x60;default&#x60; (default)   * &#x60;more&#x60; - for a more formal language   * &#x60;less&#x60; - for a more informal language   * &#x60;prefer_more&#x60; - for a more formal language if available, otherwise fallback to default formality   * &#x60;prefer_less&#x60; - for a more informal language if available, otherwise fallback to default formality
   * @return formality
  **/
  public FormalityEnum getFormality() {
    return formality;
  }

  public void setFormality(FormalityEnum formality) {
    this.formality = formality;
  }

  public V2TranslateBody1 modelType(ModelTypeEnum modelType) {
    this.modelType = modelType;
    return this;
  }

   /**
   * Specifies which DeepL model should be used for translation.  Possible values are: * &#x60;latency_optimized&#x60; (default) - uses lower latency “classic” translation models, which support all language pairs;   default value * &#x60;quality_optimized&#x60; - uses higher latency, improved quality “next-gen” translation models, which support only a   subset of language pairs; if a language pair that is not supported by next-gen models is included in the   request, it will fail. Consider using prefer_quality_optimized instead. * &#x60;prefer_quality_optimized&#x60; - prioritizes use of higher latency, improved quality “next-gen” translation models,   which support only a subset of DeepL languages; if a request includes a language pair not supported by   next-gen models, the request will fall back to latency_optimized classic models.
   * @return modelType
  **/
  public ModelTypeEnum getModelType() {
    return modelType;
  }

  public void setModelType(ModelTypeEnum modelType) {
    this.modelType = modelType;
  }

  public V2TranslateBody1 glossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
    return this;
  }

   /**
   * Specify the glossary to use for the translation. **Important:** This requires the &#x60;source_lang&#x60; parameter to be set and the language pair of the glossary has to match the language pair of the request.
   * @return glossaryId
  **/
  public String getGlossaryId() {
    return glossaryId;
  }

  public void setGlossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
  }

  public V2TranslateBody1 tagHandling(TagHandlingEnum tagHandling) {
    this.tagHandling = tagHandling;
    return this;
  }

   /**
   * Sets which kind of tags should be handled. Options currently available:  * &#x60;xml&#x60;: Enable XML tag handling; see [XML Handling](https://www.deepl.com/docs-api/xml).  * &#x60;html&#x60;: Enable HTML tag handling; see [HTML Handling](https://www.deepl.com/docs-api/html).
   * @return tagHandling
  **/
  public TagHandlingEnum getTagHandling() {
    return tagHandling;
  }

  public void setTagHandling(TagHandlingEnum tagHandling) {
    this.tagHandling = tagHandling;
  }

  public V2TranslateBody1 tagHandlingVersion(TagHandlingVersionEnum tagHandlingVersion) {
    this.tagHandlingVersion = tagHandlingVersion;
    return this;
  }

   /**
   * Sets which version of the tag handling algorithm should be used. Options currently available:  * &#x60;v2&#x60;: Improved algorithm released in October 2025 (default as of December 2025).  * &#x60;v1&#x60;: Traditional algorithm (default until December 2025).
   * @return tagHandlingVersion
  **/
  public TagHandlingVersionEnum getTagHandlingVersion() {
    return tagHandlingVersion;
  }

  public void setTagHandlingVersion(TagHandlingVersionEnum tagHandlingVersion) {
    this.tagHandlingVersion = tagHandlingVersion;
  }

  public V2TranslateBody1 outlineDetection(OutlineDetectionEnum outlineDetection) {
    this.outlineDetection = outlineDetection;
    return this;
  }

   /**
   * The automatic detection of the XML structure won&#x27;t yield best results in all XML files. You can disable this automatic mechanism altogether by setting the &#x60;outline_detection&#x60; parameter to &#x60;0&#x60; and selecting the tags that should be considered structure tags. This will split sentences using the &#x60;splitting_tags&#x60; parameter.   In the example below, we achieve the same results as the automatic engine by disabling automatic detection with &#x60;outline_detection&#x3D;0&#x60; and setting the parameters manually to &#x60;tag_handling&#x3D;xml&#x60;, &#x60;split_sentences&#x3D;nonewlines&#x60;,  and &#x60;splitting_tags&#x3D;par,title&#x60;.  * Example request:    &#x60;&#x60;&#x60;    &lt;document&gt;      &lt;meta&gt;        &lt;title&gt;A document&#x27;s title&lt;/title&gt;      &lt;/meta&gt;      &lt;content&gt;        &lt;par&gt;This is the first sentence. Followed by a second one.&lt;/par&gt;        &lt;par&gt;This is the third sentence.&lt;/par&gt;      &lt;/content&gt;    &lt;/document&gt;    &#x60;&#x60;&#x60;  * Example response:    &#x60;&#x60;&#x60;    &lt;document&gt;      &lt;meta&gt;        &lt;title&gt;Der Titel eines Dokuments&lt;/title&gt;      &lt;/meta&gt;      &lt;content&gt;        &lt;par&gt;Das ist der erste Satz. Gefolgt von einem zweiten.&lt;/par&gt;        &lt;par&gt;Dies ist der dritte Satz.&lt;/par&gt;      &lt;/content&gt;    &lt;/document&gt;    &#x60;&#x60;&#x60; While this approach is slightly more complicated, it allows for greater control over the structure of the translation output.
   * @return outlineDetection
  **/
  public OutlineDetectionEnum getOutlineDetection() {
    return outlineDetection;
  }

  public void setOutlineDetection(OutlineDetectionEnum outlineDetection) {
    this.outlineDetection = outlineDetection;
  }

  public V2TranslateBody1 nonSplittingTags(String nonSplittingTags) {
    this.nonSplittingTags = nonSplittingTags;
    return this;
  }

   /**
   * Comma-separated list of XML tags which never split sentences.   For some XML files, finding tags with textual content and splitting sentences using those tags won&#x27;t yield the best results. The following example shows the engine splitting sentences on &#x60;par&#x60; tags and proceeding to translate the parts separately, resulting in an incorrect translation:  * Example request: &#x60;&#x60;&#x60; &lt;par&gt;The firm said it had been &lt;/par&gt;&lt;par&gt; conducting an internal investigation.&lt;/par&gt; &#x60;&#x60;&#x60;  * Example response: &#x60;&#x60;&#x60; &lt;par&gt;Die Firma sagte, es sei eine gute Idee gewesen.&lt;/par&gt;&lt;par&gt; Durchführung einer internen Untersuchung.&lt;/par&gt; &#x60;&#x60;&#x60;   As this can lead to bad translations, this type of structure should either be avoided, or the &#x60;non_splitting_tags&#x60; parameter should be set. The following example shows the same call, with the parameter set to &#x60;par&#x60;:  * Example request: &#x60;&#x60;&#x60; &lt;par&gt;The firm said it had been &lt;/par&gt;&lt;par&gt; conducting an internal investigation.&lt;/par&gt; &#x60;&#x60;&#x60;  * Example response: &#x60;&#x60;&#x60; &lt;par&gt;Die Firma sagte, dass sie&lt;/par&gt;&lt;par&gt; eine interne Untersuchung durchgeführt&lt;/par&gt;&lt;par&gt; habe&lt;/par&gt;&lt;par&gt;.&lt;/par&gt; &#x60;&#x60;&#x60;   This time, the sentence is translated as a whole. The XML tags are now considered markup and copied into the translated sentence. As the translation of the words \&quot;had been\&quot; has moved to another position in the German sentence, the two par tags are duplicated (which is expected here).
   * @return nonSplittingTags
  **/
  public String getNonSplittingTags() {
    return nonSplittingTags;
  }

  public void setNonSplittingTags(String nonSplittingTags) {
    this.nonSplittingTags = nonSplittingTags;
  }

  public V2TranslateBody1 splittingTags(String splittingTags) {
    this.splittingTags = splittingTags;
    return this;
  }

   /**
   * Comma-separated list of XML tags which always cause splits.   See the example in the &#x60;outline_detection&#x60; parameter&#x27;s description.
   * @return splittingTags
  **/
  public String getSplittingTags() {
    return splittingTags;
  }

  public void setSplittingTags(String splittingTags) {
    this.splittingTags = splittingTags;
  }

  public V2TranslateBody1 ignoreTags(String ignoreTags) {
    this.ignoreTags = ignoreTags;
    return this;
  }

   /**
   * Comma-separated list of XML tags that indicate text not to be translated.   Use this parameter to ensure that elements in the original text are not altered in the translation (e.g., trademarks, product names) and insert tags into your original text. In the following example, the &#x60;ignore_tags&#x60; parameter is set to &#x60;keep&#x60;:  * Example request:    &#x60;&#x60;&#x60;    Please open the page &lt;keep&gt;Settings&lt;/keep&gt; to configure your system.    &#x60;&#x60;&#x60;  * Example response:    &#x60;&#x60;&#x60;    Bitte öffnen Sie die Seite &lt;keep&gt;Settings&lt;/keep&gt; um Ihr System zu konfigurieren.    &#x60;&#x60;&#x60;
   * @return ignoreTags
  **/
  public String getIgnoreTags() {
    return ignoreTags;
  }

  public void setIgnoreTags(String ignoreTags) {
    this.ignoreTags = ignoreTags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2TranslateBody1 v2TranslateBody1 = (V2TranslateBody1) o;
    return Objects.equals(this.text, v2TranslateBody1.text) &&
        Objects.equals(this.sourceLang, v2TranslateBody1.sourceLang) &&
        Objects.equals(this.targetLang, v2TranslateBody1.targetLang) &&
        Objects.equals(this.context, v2TranslateBody1.context) &&
        Objects.equals(this.showBilledCharacters, v2TranslateBody1.showBilledCharacters) &&
        Objects.equals(this.splitSentences, v2TranslateBody1.splitSentences) &&
        Objects.equals(this.preserveFormatting, v2TranslateBody1.preserveFormatting) &&
        Objects.equals(this.formality, v2TranslateBody1.formality) &&
        Objects.equals(this.modelType, v2TranslateBody1.modelType) &&
        Objects.equals(this.glossaryId, v2TranslateBody1.glossaryId) &&
        Objects.equals(this.tagHandling, v2TranslateBody1.tagHandling) &&
        Objects.equals(this.tagHandlingVersion, v2TranslateBody1.tagHandlingVersion) &&
        Objects.equals(this.outlineDetection, v2TranslateBody1.outlineDetection) &&
        Objects.equals(this.nonSplittingTags, v2TranslateBody1.nonSplittingTags) &&
        Objects.equals(this.splittingTags, v2TranslateBody1.splittingTags) &&
        Objects.equals(this.ignoreTags, v2TranslateBody1.ignoreTags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, sourceLang, targetLang, context, showBilledCharacters, splitSentences, preserveFormatting, formality, modelType, glossaryId, tagHandling, tagHandlingVersion, outlineDetection, nonSplittingTags, splittingTags, ignoreTags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2TranslateBody1 {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    sourceLang: ").append(toIndentedString(sourceLang)).append("\n");
    sb.append("    targetLang: ").append(toIndentedString(targetLang)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    showBilledCharacters: ").append(toIndentedString(showBilledCharacters)).append("\n");
    sb.append("    splitSentences: ").append(toIndentedString(splitSentences)).append("\n");
    sb.append("    preserveFormatting: ").append(toIndentedString(preserveFormatting)).append("\n");
    sb.append("    formality: ").append(toIndentedString(formality)).append("\n");
    sb.append("    modelType: ").append(toIndentedString(modelType)).append("\n");
    sb.append("    glossaryId: ").append(toIndentedString(glossaryId)).append("\n");
    sb.append("    tagHandling: ").append(toIndentedString(tagHandling)).append("\n");
    sb.append("    tagHandlingVersion: ").append(toIndentedString(tagHandlingVersion)).append("\n");
    sb.append("    outlineDetection: ").append(toIndentedString(outlineDetection)).append("\n");
    sb.append("    nonSplittingTags: ").append(toIndentedString(nonSplittingTags)).append("\n");
    sb.append("    splittingTags: ").append(toIndentedString(splittingTags)).append("\n");
    sb.append("    ignoreTags: ").append(toIndentedString(ignoreTags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
