/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Source language of the audio stream. Must be one of the supported Voice API source languages. Language identifier must comply with IETF BCP 47 language tags.
 */
public enum VoiceSourceLanguage {
  ZH("zh"),
  NL("nl"),
  EN("en"),
  FR("fr"),
  DE("de"),
  ID("id"),
  IT("it"),
  JA("ja"),
  KO("ko"),
  PL("pl"),
  PT("pt"),
  RO("ro"),
  RU("ru"),
  ES("es"),
  SV("sv"),
  TR("tr"),
  UK("uk");

  private String value;

  VoiceSourceLanguage(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static VoiceSourceLanguage fromValue(String input) {
    for (VoiceSourceLanguage b : VoiceSourceLanguage.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
