/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * VoiceRealtimeBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class VoiceRealtimeBody {
  /**
   * The audio format for streaming. Specifies container, codec, and encoding parameters. Supported formats include PCM (recommended), OPUS (recommended for low bandwidth), FLAC, MP3, and AAC. PCM formats require explicit sample rate. Mono audio only.
   */
  public enum SourceMediaContentTypeEnum {
    AUTO("audio/auto"),
    FLAC("audio/flac"),
    MPEG("audio/mpeg"),
    OGG("audio/ogg"),
    WEBM("audio/webm"),
    X_MATROSKA("audio/x-matroska"),
    OGG_CODECS_FLAC("audio/ogg; codecs=flac"),
    OGG_CODECS_OPUS("audio/ogg; codecs=opus"),
    PCM_ENCODING_S16LE_RATE_8000("audio/pcm; encoding=s16le; rate=8000"),
    PCM_ENCODING_S16LE_RATE_16000("audio/pcm; encoding=s16le; rate=16000"),
    PCM_ENCODING_S16LE_RATE_44100("audio/pcm; encoding=s16le; rate=44100"),
    PCM_ENCODING_S16LE_RATE_48000("audio/pcm; encoding=s16le; rate=48000"),
    WEBM_CODECS_OPUS("audio/webm; codecs=opus"),
    X_MATROSKA_CODECS_AAC("audio/x-matroska; codecs=aac"),
    X_MATROSKA_CODECS_FLAC("audio/x-matroska; codecs=flac"),
    X_MATROSKA_CODECS_MP3("audio/x-matroska; codecs=mp3"),
    X_MATROSKA_CODECS_OPUS("audio/x-matroska; codecs=opus");

    private String value;

    SourceMediaContentTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceMediaContentTypeEnum fromValue(String input) {
      for (SourceMediaContentTypeEnum b : SourceMediaContentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_media_content_type")
  private SourceMediaContentTypeEnum sourceMediaContentType = null;

  /**
   * Source language of the audio stream. Must be one of the supported Voice API source languages. Language identifier must comply with IETF BCP 47 language tags.
   */
  public enum SourceLanguageEnum {
    ZH("zh"),
    NL("nl"),
    EN("en"),
    FR("fr"),
    DE("de"),
    ID("id"),
    IT("it"),
    JA("ja"),
    KO("ko"),
    PL("pl"),
    PT("pt"),
    RO("ro"),
    RU("ru"),
    ES("es"),
    SV("sv"),
    TR("tr"),
    UK("uk");

    private String value;

    SourceLanguageEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceLanguageEnum fromValue(String input) {
      for (SourceLanguageEnum b : SourceLanguageEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_language")
  private SourceLanguageEnum sourceLanguage = null;

  /**
   * Controls how the source_language value is used. - &#x60;auto&#x60;: Treats source language as a hint; server can override - &#x60;fixed&#x60;: Treats source language as mandatory; server must use this language
   */
  public enum SourceLanguageModeEnum {
    AUTO("auto"),
    FIXED("fixed");

    private String value;

    SourceLanguageModeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SourceLanguageModeEnum fromValue(String input) {
      for (SourceLanguageModeEnum b : SourceLanguageModeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("source_language_mode")
  private SourceLanguageModeEnum sourceLanguageMode = SourceLanguageModeEnum.AUTO;

  @JsonProperty("target_languages")
  private List<String> targetLanguages = null;

  @JsonProperty("glossary_id")
  private String glossaryId = null;

  /**
   * Sets whether the translated text should lean towards formal or informal language. Possible options are:   * &#x60;default&#x60; - use the default formality for the target language   * &#x60;formal&#x60;/&#x60;more&#x60; - for a more formal language   * &#x60;informal&#x60;/&#x60;less&#x60; - for a more informal language
   */
  public enum FormalityEnum {
    DEFAULT("default"),
    FORMAL("formal"),
    MORE("more"),
    INFORMAL("informal"),
    LESS("less");

    private String value;

    FormalityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FormalityEnum fromValue(String input) {
      for (FormalityEnum b : FormalityEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("formality")
  private FormalityEnum formality = FormalityEnum.DEFAULT;

  public VoiceRealtimeBody sourceMediaContentType(SourceMediaContentTypeEnum sourceMediaContentType) {
    this.sourceMediaContentType = sourceMediaContentType;
    return this;
  }

   /**
   * The audio format for streaming. Specifies container, codec, and encoding parameters. Supported formats include PCM (recommended), OPUS (recommended for low bandwidth), FLAC, MP3, and AAC. PCM formats require explicit sample rate. Mono audio only.
   * @return sourceMediaContentType
  **/
  public SourceMediaContentTypeEnum getSourceMediaContentType() {
    return sourceMediaContentType;
  }

  public void setSourceMediaContentType(SourceMediaContentTypeEnum sourceMediaContentType) {
    this.sourceMediaContentType = sourceMediaContentType;
  }

  public VoiceRealtimeBody sourceLanguage(SourceLanguageEnum sourceLanguage) {
    this.sourceLanguage = sourceLanguage;
    return this;
  }

   /**
   * Source language of the audio stream. Must be one of the supported Voice API source languages. Language identifier must comply with IETF BCP 47 language tags.
   * @return sourceLanguage
  **/
  public SourceLanguageEnum getSourceLanguage() {
    return sourceLanguage;
  }

  public void setSourceLanguage(SourceLanguageEnum sourceLanguage) {
    this.sourceLanguage = sourceLanguage;
  }

  public VoiceRealtimeBody sourceLanguageMode(SourceLanguageModeEnum sourceLanguageMode) {
    this.sourceLanguageMode = sourceLanguageMode;
    return this;
  }

   /**
   * Controls how the source_language value is used. - &#x60;auto&#x60;: Treats source language as a hint; server can override - &#x60;fixed&#x60;: Treats source language as mandatory; server must use this language
   * @return sourceLanguageMode
  **/
  public SourceLanguageModeEnum getSourceLanguageMode() {
    return sourceLanguageMode;
  }

  public void setSourceLanguageMode(SourceLanguageModeEnum sourceLanguageMode) {
    this.sourceLanguageMode = sourceLanguageMode;
  }

  public VoiceRealtimeBody targetLanguages(List<String> targetLanguages) {
    this.targetLanguages = targetLanguages;
    return this;
  }

  public VoiceRealtimeBody addTargetLanguagesItem(String targetLanguagesItem) {
    if (this.targetLanguages == null) {
      this.targetLanguages = new ArrayList<>();
    }
    this.targetLanguages.add(targetLanguagesItem);
    return this;
  }

   /**
   * List of target languages for translation. The stream will emit translations for each language. Maximum 5 target languages per stream. Language identifiers must comply with IETF BCP 47.
   * @return targetLanguages
  **/
  public List<String> getTargetLanguages() {
    return targetLanguages;
  }

  public void setTargetLanguages(List<String> targetLanguages) {
    this.targetLanguages = targetLanguages;
  }

  public VoiceRealtimeBody glossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
    return this;
  }

   /**
   * A unique ID assigned to a glossary.
   * @return glossaryId
  **/
  public String getGlossaryId() {
    return glossaryId;
  }

  public void setGlossaryId(String glossaryId) {
    this.glossaryId = glossaryId;
  }

  public VoiceRealtimeBody formality(FormalityEnum formality) {
    this.formality = formality;
    return this;
  }

   /**
   * Sets whether the translated text should lean towards formal or informal language. Possible options are:   * &#x60;default&#x60; - use the default formality for the target language   * &#x60;formal&#x60;/&#x60;more&#x60; - for a more formal language   * &#x60;informal&#x60;/&#x60;less&#x60; - for a more informal language
   * @return formality
  **/
  public FormalityEnum getFormality() {
    return formality;
  }

  public void setFormality(FormalityEnum formality) {
    this.formality = formality;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoiceRealtimeBody voiceRealtimeBody = (VoiceRealtimeBody) o;
    return Objects.equals(this.sourceMediaContentType, voiceRealtimeBody.sourceMediaContentType) &&
        Objects.equals(this.sourceLanguage, voiceRealtimeBody.sourceLanguage) &&
        Objects.equals(this.sourceLanguageMode, voiceRealtimeBody.sourceLanguageMode) &&
        Objects.equals(this.targetLanguages, voiceRealtimeBody.targetLanguages) &&
        Objects.equals(this.glossaryId, voiceRealtimeBody.glossaryId) &&
        Objects.equals(this.formality, voiceRealtimeBody.formality);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceMediaContentType, sourceLanguage, sourceLanguageMode, targetLanguages, glossaryId, formality);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoiceRealtimeBody {\n");
    
    sb.append("    sourceMediaContentType: ").append(toIndentedString(sourceMediaContentType)).append("\n");
    sb.append("    sourceLanguage: ").append(toIndentedString(sourceLanguage)).append("\n");
    sb.append("    sourceLanguageMode: ").append(toIndentedString(sourceLanguageMode)).append("\n");
    sb.append("    targetLanguages: ").append(toIndentedString(targetLanguages)).append("\n");
    sb.append("    glossaryId: ").append(toIndentedString(glossaryId)).append("\n");
    sb.append("    formality: ").append(toIndentedString(formality)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
