/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Controls how the source_language value is used. - &#x60;auto&#x60;: Treats source language as a hint; server can override - &#x60;fixed&#x60;: Treats source language as mandatory; server must use this language
 */
public enum VoiceSourceLanguageMode {
  AUTO("auto"),
  FIXED("fixed");

  private String value;

  VoiceSourceLanguageMode(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static VoiceSourceLanguageMode fromValue(String input) {
    for (VoiceSourceLanguageMode b : VoiceSourceLanguageMode.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
