/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sets whether the translated text should lean towards formal or informal language. Possible options are:   * &#x60;default&#x60; - use the default formality for the target language   * &#x60;formal&#x60;/&#x60;more&#x60; - for a more formal language   * &#x60;informal&#x60;/&#x60;less&#x60; - for a more informal language
 */
public enum VoiceFormality {
  DEFAULT("default"),
  FORMAL("formal"),
  MORE("more"),
  INFORMAL("informal"),
  LESS("less");

  private String value;

  VoiceFormality(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static VoiceFormality fromValue(String input) {
    for (VoiceFormality b : VoiceFormality.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
