/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The audio format for streaming. Specifies container, codec, and encoding parameters. Supported formats include PCM (recommended), OPUS (recommended for low bandwidth), FLAC, MP3, and AAC. PCM formats require explicit sample rate. Mono audio only.
 */
public enum VoiceMediaContentType {
  AUTO("audio/auto"),
  FLAC("audio/flac"),
  MPEG("audio/mpeg"),
  OGG("audio/ogg"),
  WEBM("audio/webm"),
  X_MATROSKA("audio/x-matroska"),
  OGG_CODECS_FLAC("audio/ogg; codecs=flac"),
  OGG_CODECS_OPUS("audio/ogg; codecs=opus"),
  PCM_ENCODING_S16LE_RATE_8000("audio/pcm; encoding=s16le; rate=8000"),
  PCM_ENCODING_S16LE_RATE_16000("audio/pcm; encoding=s16le; rate=16000"),
  PCM_ENCODING_S16LE_RATE_44100("audio/pcm; encoding=s16le; rate=44100"),
  PCM_ENCODING_S16LE_RATE_48000("audio/pcm; encoding=s16le; rate=48000"),
  WEBM_CODECS_OPUS("audio/webm; codecs=opus"),
  X_MATROSKA_CODECS_AAC("audio/x-matroska; codecs=aac"),
  X_MATROSKA_CODECS_FLAC("audio/x-matroska; codecs=flac"),
  X_MATROSKA_CODECS_MP3("audio/x-matroska; codecs=mp3"),
  X_MATROSKA_CODECS_OPUS("audio/x-matroska; codecs=opus");

  private String value;

  VoiceMediaContentType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static VoiceMediaContentType fromValue(String input) {
    for (VoiceMediaContentType b : VoiceMediaContentType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
