/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * WriteRephraseBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-12-25T10:19:09.709120500+07:00[Asia/Bangkok]")

public class WriteRephraseBody1 {
  @JsonProperty("text")
  private List<String> text = new ArrayList<>();

  /**
   * The language for the text improvement. Options currently available:  * &#x60;de&#x60; - German  * &#x60;en&#x60; - English (unspecified variant, defaults to &#x60;en-US&#x60;)  * &#x60;en-GB&#x60; - English (British)  * &#x60;en-US&#x60; - English (American)  * &#x60;es&#x60; - Spanish  * &#x60;fr&#x60; - French  * &#x60;it&#x60; - Italian  * &#x60;pt&#x60; - Portuguese (unspecified variant, defaults to &#x60;pt-PT&#x60;)  * &#x60;pt-BR&#x60; - Portuguese (Brazilian)  * &#x60;pt-PT&#x60; - Portuguese (all Portuguese variants excluding Brazilian Portuguese)
   */
  public enum TargetLangEnum {
    DE("de"),
    EN("en"),
    EN_GB("en-GB"),
    EN_US("en-US"),
    FR("fr"),
    IT("it"),
    PT("pt"),
    PT_BR("pt-BR"),
    PT_PT("pt-PT");

    private String value;

    TargetLangEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TargetLangEnum fromValue(String input) {
      for (TargetLangEnum b : TargetLangEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("target_lang")
  private TargetLangEnum targetLang = null;

  /**
   * Specify a style to rephrase your text in a way that fits your audience and goals. The &#x60;prefer_&#x60; prefix allows falling back to the default style if the language does not yet support styles.
   */
  public enum WritingStyleEnum {
    ACADEMIC("academic"),
    BUSINESS("business"),
    CASUAL("casual"),
    DEFAULT("default"),
    SIMPLE("simple"),
    PREFER_ACADEMIC("prefer_academic"),
    PREFER_BUSINESS("prefer_business"),
    PREFER_CASUAL("prefer_casual"),
    PREFER_SIMPLE("prefer_simple");

    private String value;

    WritingStyleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static WritingStyleEnum fromValue(String input) {
      for (WritingStyleEnum b : WritingStyleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("writing_style")
  private WritingStyleEnum writingStyle = null;

  /**
   * Specify the desired tone for your text. The &#x60;prefer_&#x60; prefix allows falling back to the default tone if the language does not yet support tones.
   */
  public enum ToneEnum {
    CONFIDENT("confident"),
    DEFAULT("default"),
    DIPLOMATIC("diplomatic"),
    ENTHUSIASTIC("enthusiastic"),
    FRIENDLY("friendly"),
    PREFER_CONFIDENT("prefer_confident"),
    PREFER_DIPLOMATIC("prefer_diplomatic"),
    PREFER_ENTHUSIASTIC("prefer_enthusiastic"),
    PREFER_FRIENDLY("prefer_friendly");

    private String value;

    ToneEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ToneEnum fromValue(String input) {
      for (ToneEnum b : ToneEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("tone")
  private ToneEnum tone = null;

  public WriteRephraseBody1 text(List<String> text) {
    this.text = text;
    return this;
  }

  public WriteRephraseBody1 addTextItem(String textItem) {
    this.text.add(textItem);
    return this;
  }

   /**
   * Text to be improved. Only UTF-8-encoded plain text is supported. Improvements are returned in the same order as they are requested.
   * @return text
  **/
  public List<String> getText() {
    return text;
  }

  public void setText(List<String> text) {
    this.text = text;
  }

  public WriteRephraseBody1 targetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
    return this;
  }

   /**
   * The language for the text improvement. Options currently available:  * &#x60;de&#x60; - German  * &#x60;en&#x60; - English (unspecified variant, defaults to &#x60;en-US&#x60;)  * &#x60;en-GB&#x60; - English (British)  * &#x60;en-US&#x60; - English (American)  * &#x60;es&#x60; - Spanish  * &#x60;fr&#x60; - French  * &#x60;it&#x60; - Italian  * &#x60;pt&#x60; - Portuguese (unspecified variant, defaults to &#x60;pt-PT&#x60;)  * &#x60;pt-BR&#x60; - Portuguese (Brazilian)  * &#x60;pt-PT&#x60; - Portuguese (all Portuguese variants excluding Brazilian Portuguese)
   * @return targetLang
  **/
  public TargetLangEnum getTargetLang() {
    return targetLang;
  }

  public void setTargetLang(TargetLangEnum targetLang) {
    this.targetLang = targetLang;
  }

  public WriteRephraseBody1 writingStyle(WritingStyleEnum writingStyle) {
    this.writingStyle = writingStyle;
    return this;
  }

   /**
   * Specify a style to rephrase your text in a way that fits your audience and goals. The &#x60;prefer_&#x60; prefix allows falling back to the default style if the language does not yet support styles.
   * @return writingStyle
  **/
  public WritingStyleEnum getWritingStyle() {
    return writingStyle;
  }

  public void setWritingStyle(WritingStyleEnum writingStyle) {
    this.writingStyle = writingStyle;
  }

  public WriteRephraseBody1 tone(ToneEnum tone) {
    this.tone = tone;
    return this;
  }

   /**
   * Specify the desired tone for your text. The &#x60;prefer_&#x60; prefix allows falling back to the default tone if the language does not yet support tones.
   * @return tone
  **/
  public ToneEnum getTone() {
    return tone;
  }

  public void setTone(ToneEnum tone) {
    this.tone = tone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriteRephraseBody1 writeRephraseBody1 = (WriteRephraseBody1) o;
    return Objects.equals(this.text, writeRephraseBody1.text) &&
        Objects.equals(this.targetLang, writeRephraseBody1.targetLang) &&
        Objects.equals(this.writingStyle, writeRephraseBody1.writingStyle) &&
        Objects.equals(this.tone, writeRephraseBody1.tone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, targetLang, writingStyle, tone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriteRephraseBody1 {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    targetLang: ").append(toIndentedString(targetLang)).append("\n");
    sb.append("    writingStyle: ").append(toIndentedString(writingStyle)).append("\n");
    sb.append("    tone: ").append(toIndentedString(tone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
