/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specify the desired tone for your text. The &#x60;prefer_&#x60; prefix allows falling back to the default tone if the language does not yet support tones.
 */
public enum WritingTone {
  CONFIDENT("confident"),
  DEFAULT("default"),
  DIPLOMATIC("diplomatic"),
  ENTHUSIASTIC("enthusiastic"),
  FRIENDLY("friendly"),
  PREFER_CONFIDENT("prefer_confident"),
  PREFER_DIPLOMATIC("prefer_diplomatic"),
  PREFER_ENTHUSIASTIC("prefer_enthusiastic"),
  PREFER_FRIENDLY("prefer_friendly");

  private String value;

  WritingTone(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static WritingTone fromValue(String input) {
    for (WritingTone b : WritingTone.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
