/*
 * DeepL API Documentation
 * The DeepL API provides programmatic access to DeepL’s language AI technology.
 *
 * OpenAPI spec version: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.deepl.api.v2.client;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specify a style to rephrase your text in a way that fits your audience and goals. The &#x60;prefer_&#x60; prefix allows falling back to the default style if the language does not yet support styles.
 */
public enum WritingStyle {
  ACADEMIC("academic"),
  BUSINESS("business"),
  CASUAL("casual"),
  DEFAULT("default"),
  SIMPLE("simple"),
  PREFER_ACADEMIC("prefer_academic"),
  PREFER_BUSINESS("prefer_business"),
  PREFER_CASUAL("prefer_casual"),
  PREFER_SIMPLE("prefer_simple");

  private String value;

  WritingStyle(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static WritingStyle fromValue(String input) {
    for (WritingStyle b : WritingStyle.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }
}
