name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout deepl-mock repo
        uses: actions/checkout@v4
        with:
          repository: DeepLcom/deepl-mock
          path: deepl-mock
          ref: main

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MARKET_DOCKERHUB_USERNAME }}
          password: ${{ secrets.MARKET_DOCKERHUB_TOKEN }}

      - name: Build latest deepl test image and publish it in Octopus repo hub
        run: |
          IMAGE_NAME=octopusaxonivy/mock-deepl-server:latest
          docker build -t $IMAGE_NAME deepl-mock
          docker push $IMAGE_NAME
  build:
    needs: prepare
    permissions:
      contents: read
      actions: write
      checks: write
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6