name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: write
  actions: write
  
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Deepl-mock repo
        uses: actions/checkout@v4
        with:
          repository: DeepLcom/deepl-mock
          path: deepl-mock
          ref: main
      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MARKET_DOCKERHUB_USERNAME }}
          password: ${{ secrets.MARKET_DOCKERHUB_TOKEN }}
      - name: Build latest Deepl-mock test image and publish it in Octopus's public docker hub
        run: |
          IMAGE_NAME=octopusaxonivy/mock-deepl-server:latest
          docker build -t $IMAGE_NAME deepl-mock
          docker push $IMAGE_NAME

  build:
    needs: prepare
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
